// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demob/demoB.proto

package demob

import (
	akserver "ag-core/contribute/agkitex/server"
	fx "go.uber.org/fx"
)

// FxDemobKitexModule fx module
var FxDemobKitexModule = fx.Module("fx_Demob_kitex",
	FxDemobKitexRegProvider,
)

// FxDemobKitexRegProvider fx provide
var FxDemobKitexRegProvider = fx.Provide(

	akserver.NewFxAgKitexServiceRegistry(
		Register_Demob_KitexServer,
	),
)
