// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demob/demoB.proto

package demob

import (
	demob "agdemoB/api/demob"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var demobServiceMethods = map[string]kitex.MethodInfo{
	"calldemob": kitex.NewMethodInfo(
		calldemobHandler,
		newCalldemobArgs,
		newCalldemobResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	demobServiceInfo                = NewServiceInfo()
	demobServiceInfoForClient       = NewServiceInfoForClient()
	demobServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return demobServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return demobServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return demobServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "demob"
	handlerType := (*demob.Demob)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range demobServiceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "api.demob",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.14.1_by_aggen", // FIXME 模板生成时应该获取kitex版本
		Extra:           extra,
	}
	return svcInfo
}

func calldemobHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(demob.BRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(demob.Demob).Calldemob(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CalldemobArgs:
		success, err := handler.(demob.Demob).Calldemob(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CalldemobResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCalldemobArgs() interface{} {
	return &CalldemobArgs{}
}

func newCalldemobResult() interface{} {
	return &CalldemobResult{}
}

type CalldemobArgs struct {
	Req *demob.BRequest
}

func (p *CalldemobArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CalldemobArgs) Unmarshal(in []byte) error {
	msg := new(demob.BRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CalldemobArgs_Req_DEFAULT *demob.BRequest

func (p *CalldemobArgs) GetReq() *demob.BRequest {
	if !p.IsSetReq() {
		return CalldemobArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CalldemobArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CalldemobArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CalldemobResult struct {
	Success *demob.BReply
}

var CalldemobResult_Success_DEFAULT *demob.BReply

func (p *CalldemobResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CalldemobResult) Unmarshal(in []byte) error {
	msg := new(demob.BReply)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CalldemobResult) GetSuccess() *demob.BReply {
	if !p.IsSetSuccess() {
		return CalldemobResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CalldemobResult) SetSuccess(x interface{}) {
	p.Success = x.(*demob.BReply)
}

func (p *CalldemobResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CalldemobResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Calldemob(ctx context.Context, Req *demob.BRequest) (r *demob.BReply, err error) {
	var _args CalldemobArgs
	_args.Req = Req
	var _result CalldemobResult
	if err = p.c.Call(ctx, "calldemob", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
