// Code generated by aic-generate, DO NOT EDIT
// Code generated by aic-generate, DO NOT EDIT
// Code generated by aic-generate, DO NOT EDIT

package dao

import (
	db "ag-core/contribute/agdb/gormdb"
	"agdemoB/internal/repository/model"
	"context"
	"errors"

	agdao "ag-core/contribute/agdb/agdao"
	"strings"

	"gorm.io/gorm"
)

var StudentNamingSqlMap = map[string]string{}

// insert忽略空值时标记哪些字段需要排除在外
var excludeStudentZeroColNames = map[string]int{"Fct": 0, "Lct": 0}

type IStudentDao interface {
	InsertOne(ctx context.Context, arg *model.Student) (int64, error)
	InsertOneIgnorenNullCols(ctx context.Context, arg *model.Student) (int64, error)
	FindByPrimaryKey(ctx context.Context, Id int64) (*model.Student, error)
	UpdateByPrimaryKey(ctx context.Context, arg *model.Student) (int64, error)
	UpdateByPriIngoreNullCols(ctx context.Context, arg *model.Student) (int64, error)
	DeleteByPrimaryKey(ctx context.Context, Id int64) (int64, error)

	FindByNameAge(ctx context.Context, Name string, Age int) ([]model.Student, error)
	FindByStuno(ctx context.Context, Stuno int64) (*model.Student, error)

	UpdateByStuno(ctx context.Context, Stuno int64, arg *model.Student) (int64, error)
	DeleteByStuno(ctx context.Context, Stuno int64) (int64, error)

	// 查询指定列
	FindByAge(ctx context.Context, arg *model.StudentFindByAgeArg) ([]*model.StudentFindByAgeRes, error)

	// 查询全部列
	FindByWithPage(ctx context.Context, arg *model.StudentFindByWithPageArg) ([]*model.Student, error)
}

type StudentDao struct {
	*db.Repository
	info    agdao.TableInfo
	baseDao agdao.BaseDao
}

// NewStudentDao get dao instance
func NewStudentDao(repository *db.Repository, baseDao agdao.BaseDao) IStudentDao {
	InitStudentNamingSql()
	return &StudentDao{
		Repository: repository,
		baseDao:    baseDao,
		info: agdao.TableInfo{
			TableName: "student",
		},
	}
}

// InsertOne 插入数据
func (dao *StudentDao) InsertOne(ctx context.Context, arg *model.Student) (int64, error) {
	db, err := dao.newDB(ctx)
	if err != nil {
		return 0, err
	}
	result := db.Create(arg)
	return result.RowsAffected, result.Error
}

// InsertOneIgnorenNullCols 插入数据时，自动剔除零值的列
func (dao *StudentDao) InsertOneIgnorenNullCols(ctx context.Context, arg *model.Student) (int64, error) {
	insertIgnoreZeroValSlice := db.CollectZeroValWithOmitEmpty(arg, excludeStudentZeroColNames)
	db, err := dao.newDB(ctx)
	if err != nil {
		return 0, err
	}
	result := db.Omit(insertIgnoreZeroValSlice...).Create(arg)
	return result.RowsAffected, result.Error
}

func (dao *StudentDao) FindByPrimaryKey(ctx context.Context, Id int64) (*model.Student, error) {
	findRes := &model.Student{}
	db, err := dao.newDB(ctx)
	if err != nil {
		return nil, err
	}
	db = db.Where("ID", Id)
	result := db.Find(findRes)
	return findRes, result.Error
}

// UpdateByPrimaryKey 根据主键更新，该操作只适合从数据库查询原实体修改值之后使用
func (dao *StudentDao) UpdateByPrimaryKey(ctx context.Context, arg *model.Student) (int64, error) {

	db, err := dao.newDB(ctx)
	if err != nil {
		return 0, err
	}
	result := db.Save(arg)
	return result.RowsAffected, result.Error
}

// UpdateByPriIngoreNullCols 根据主键更新，自动剔除参数中的零值列
func (dao *StudentDao) UpdateByPriIngoreNullCols(ctx context.Context, arg *model.Student) (int64, error) {

	db, err := dao.newDB(ctx)
	if err != nil {
		return 0, err
	}
	result := db.Model(arg).Updates(arg)
	return result.RowsAffected, result.Error
}

func (dao *StudentDao) DeleteByPrimaryKey(ctx context.Context, Id int64) (int64, error) {

	db, err := dao.newDB(ctx)
	if err != nil {
		return 0, err
	}
	result := db.Where("ID", Id).Delete(&model.Student{})
	return result.RowsAffected, result.Error
}

func (dao *StudentDao) FindByNameAge(ctx context.Context, Name string, Age int) ([]model.Student, error) {
	var list []model.Student
	db, err := dao.newDB(ctx)
	if err != nil {
		return nil, err
	}
	result := db.Where("NAME", Name).Where("AGE", Age).Find(&list)
	return list, result.Error
}

func (dao *StudentDao) FindByStuno(ctx context.Context, Stuno int64) (*model.Student, error) {
	findRes := &model.Student{}
	db, err := dao.newDB(ctx)
	if err != nil {
		return nil, err
	}
	result := db.Where("STUNO", Stuno).Find(findRes)
	return findRes, result.Error
}

// UpdateByStuno 根据唯一索引更新数据,自动剔除零值的列
func (dao *StudentDao) UpdateByStuno(ctx context.Context, Stuno int64, arg *model.Student) (int64, error) {
	db, err := dao.newDB(ctx)
	if err != nil {
		return 0, err
	}
	result := db.Model(&model.Student{}).Where("STUNO", Stuno).Updates(arg)
	return result.RowsAffected, result.Error
}

// DeleteByStuno 根据唯一索引作为条件,删除满足条件的数据
func (dao *StudentDao) DeleteByStuno(ctx context.Context, Stuno int64) (int64, error) {
	db, err := dao.newDB(ctx)
	if err != nil {
		return 0, err
	}
	result := db.Where("STUNO", Stuno).Delete(&model.Student{})
	return result.RowsAffected, result.Error
}

// 查询全部列
func (dao *StudentDao) FindByAge(ctx context.Context, arg *model.StudentFindByAgeArg) ([]*model.StudentFindByAgeRes, error) {
	var list []*model.StudentFindByAgeRes

	sqlName := StudentNamingSqlMap[dao.DbType+"_Student_FindByAge"]
	if sqlName == "" {
		return nil, errors.New("不支持的db类型")
	}
	newTableName := dao.getApplyInfo(ctx).TableName
	if newTableName != "" {
		enity := &model.Student{}
		sqlName = strings.ReplaceAll(sqlName, "FROM "+enity.TableName()+" WHERE", "FROM "+newTableName+" WHERE")
	}
	result := dao.DB(ctx).Raw(sqlName, arg).Find(&list)
	return list, result.Error
}

// 查询全部列
func (dao *StudentDao) FindByWithPage(ctx context.Context, arg *model.StudentFindByWithPageArg) ([]*model.Student, error) {
	var list []*model.Student

	sqlName := StudentNamingSqlMap[dao.DbType+"_Student_FindByWithPage"]
	if sqlName == "" {
		return nil, errors.New("不支持的db类型")
	}
	newTableName := dao.getApplyInfo(ctx).TableName
	if newTableName != "" {
		enity := &model.Student{}
		sqlName = strings.ReplaceAll(sqlName, "FROM "+enity.TableName()+" WHERE", "FROM "+newTableName+" WHERE")
	}
	result := dao.DB(ctx).Raw(sqlName, arg).Find(&list)
	return list, result.Error
}

func (dao *StudentDao) getInfo() agdao.TableInfo {
	return dao.info
}

func (dao *StudentDao) getApplyInfo(ctx context.Context) agdao.TableInfo {
	info := dao.getInfo()                   // 获取info副本
	dao.baseDao.ApplyTbInfoOpts(ctx, &info) // 对副本info进行增强
	return info
}

// newDB 创建一个新的DB实例，应用增强后的TableInfo
func (dao *StudentDao) newDB(ctx context.Context) (*gorm.DB, error) {
	db := dao.DB(ctx)

	info := dao.getApplyInfo(ctx)

	tbname := info.TableName
	if tbname == "" {
		return nil, errors.New("表名不能为空")
	}
	db = db.Table(tbname)
	return db, nil
}
