// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressa/stressa.proto

package adpinit

import (
	aservice "ag_stress_a/internal/adpgen/hertz/aservice"
)

func init() {
	AddFxAdapterOpt(aservice.FxAServiceHertzModule)
}
