// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressa/stressa.proto

package adpinit

import (
	aservice "ag_stress_a/internal/adpgen/kitex/aservice"
)

func init() {
	AddFxAdapterOpt(aservice.FxAServiceKitexModule)
}
