// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressc/stressc.proto

package cservice

import (
	agclient "ag-core/contribute/agkitex/client"
	client "github.com/cloudwego/kitex/client"
)

// NewClientWithSuite Create a new client with the given suite.
func NewClientWithSuite(destService string, suite *agclient.KitexClientSuite, opts ...client.Option) (Client, error) {
	allOpts := append([]client.Option{client.WithSuite(suite)}, opts...)
	return NewClient(destService, allOpts...)
}
