// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressc/stressc.proto

package cservice

import (
	stressc "ag_stress_c/api/stressc"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var cServiceServiceMethods = map[string]kitex.MethodInfo{
	"echoC": kitex.NewMethodInfo(
		echoCHandler,
		newEchoCArgs,
		newEchoCResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	cServiceServiceInfo                = NewServiceInfo()
	cServiceServiceInfoForClient       = NewServiceInfoForClient()
	cServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return cServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return cServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return cServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "cService"
	handlerType := (*stressc.CService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range cServiceServiceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "stressc",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.14.1_by_aggen", // FIXME 模板生成时应该获取kitex版本
		Extra:           extra,
	}
	return svcInfo
}

func echoCHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(stressc.EchoCRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(stressc.CService).EchoC(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *EchoCArgs:
		success, err := handler.(stressc.CService).EchoC(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*EchoCResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newEchoCArgs() interface{} {
	return &EchoCArgs{}
}

func newEchoCResult() interface{} {
	return &EchoCResult{}
}

type EchoCArgs struct {
	Req *stressc.EchoCRequest
}

func (p *EchoCArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *EchoCArgs) Unmarshal(in []byte) error {
	msg := new(stressc.EchoCRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var EchoCArgs_Req_DEFAULT *stressc.EchoCRequest

func (p *EchoCArgs) GetReq() *stressc.EchoCRequest {
	if !p.IsSetReq() {
		return EchoCArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *EchoCArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *EchoCArgs) GetFirstArgument() interface{} {
	return p.Req
}

type EchoCResult struct {
	Success *stressc.EchoCResponse
}

var EchoCResult_Success_DEFAULT *stressc.EchoCResponse

func (p *EchoCResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *EchoCResult) Unmarshal(in []byte) error {
	msg := new(stressc.EchoCResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *EchoCResult) GetSuccess() *stressc.EchoCResponse {
	if !p.IsSetSuccess() {
		return EchoCResult_Success_DEFAULT
	}
	return p.Success
}

func (p *EchoCResult) SetSuccess(x interface{}) {
	p.Success = x.(*stressc.EchoCResponse)
}

func (p *EchoCResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EchoCResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) EchoC(ctx context.Context, Req *stressc.EchoCRequest) (r *stressc.EchoCResponse, err error) {
	var _args EchoCArgs
	_args.Req = Req
	var _result EchoCResult
	if err = p.c.Call(ctx, "echoC", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
