// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
//
// GenScope: package_group
// Versions:
//   - agserver: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demoa/demoA.proto

package demoa

import (
	"context"
)

// DemoA defines the server interface for the DemoA service.
type DemoA interface {
	Calldemoa(context.Context, *ARequest) (*AReply, error)
}
