// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: demoa/demoA.proto

package demoa

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ARequest) Reset() {
	*x = ARequest{}
	mi := &file_demoa_demoA_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ARequest) ProtoMessage() {}

func (x *ARequest) ProtoReflect() protoreflect.Message {
	mi := &file_demoa_demoA_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ARequest.ProtoReflect.Descriptor instead.
func (*ARequest) Descriptor() ([]byte, []int) {
	return file_demoa_demoA_proto_rawDescGZIP(), []int{0}
}

func (x *ARequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AReply) Reset() {
	*x = AReply{}
	mi := &file_demoa_demoA_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AReply) ProtoMessage() {}

func (x *AReply) ProtoReflect() protoreflect.Message {
	mi := &file_demoa_demoA_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AReply.ProtoReflect.Descriptor instead.
func (*AReply) Descriptor() ([]byte, []int) {
	return file_demoa_demoA_proto_rawDescGZIP(), []int{1}
}

func (x *AReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_demoa_demoA_proto protoreflect.FileDescriptor

const file_demoa_demoA_proto_rawDesc = "" +
	"\n" +
	"\x11demoa/demoA.proto\x12\x05demoa\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/descriptor.proto\"\x1e\n" +
	"\bARequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1a\n" +
	"\x06AReply\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2M\n" +
	"\x05DemoA\x12D\n" +
	"\tcalldemoa\x12\x0f.demoa.ARequest\x1a\r.demoa.AReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*b\x01*\"\tcalldemoAB\x13Z\x11agdemoA/api/demoab\x06proto3"

var (
	file_demoa_demoA_proto_rawDescOnce sync.Once
	file_demoa_demoA_proto_rawDescData []byte
)

func file_demoa_demoA_proto_rawDescGZIP() []byte {
	file_demoa_demoA_proto_rawDescOnce.Do(func() {
		file_demoa_demoA_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_demoa_demoA_proto_rawDesc), len(file_demoa_demoA_proto_rawDesc)))
	})
	return file_demoa_demoA_proto_rawDescData
}

var file_demoa_demoA_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_demoa_demoA_proto_goTypes = []any{
	(*ARequest)(nil), // 0: demoa.ARequest
	(*AReply)(nil),   // 1: demoa.AReply
}
var file_demoa_demoA_proto_depIdxs = []int32{
	0, // 0: demoa.DemoA.calldemoa:input_type -> demoa.ARequest
	1, // 1: demoa.DemoA.calldemoa:output_type -> demoa.AReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_demoa_demoA_proto_init() }
func file_demoa_demoA_proto_init() {
	if File_demoa_demoA_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_demoa_demoA_proto_rawDesc), len(file_demoa_demoA_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demoa_demoA_proto_goTypes,
		DependencyIndexes: file_demoa_demoA_proto_depIdxs,
		MessageInfos:      file_demoa_demoA_proto_msgTypes,
	}.Build()
	File_demoa_demoA_proto = out.File
	file_demoa_demoA_proto_goTypes = nil
	file_demoa_demoA_proto_depIdxs = nil
}
