// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
//
// GenScope: package_group
// Versions:
//   - agserver: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - hello/hello.proto

package hello

import (
	"context"
)

// Hello defines the server interface for the Hello service.
type Hello interface {
	Pinghello(context.Context, *HelloRequest) (*HelloReply, error)
}
