// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
//
// GenScope: package_group
// Versions:
//   - agserver: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - pos_management/pos_management.proto

package pos_management

import (
	common "agdemoapi/api/common"
	"context"
)

// PosManagement defines the server interface for the PosManagement service.
type PosManagement interface {
	SignIn(context.Context, *common.CommonReq) (*common.CommonRep, error)
}
