// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pos_management/pos_management.proto

package pos_management

import (
	common "agdemoapi/api/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_pos_management_pos_management_proto protoreflect.FileDescriptor

const file_pos_management_pos_management_proto_rawDesc = "" +
	"\n" +
	"#pos_management/pos_management.proto\x12\x0epos_management\x1a\x13common/common.proto\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/descriptor.proto2V\n" +
	"\rPosManagement\x12E\n" +
	"\x06SignIn\x12\x11.common.CommonReq\x1a\x11.common.CommonRep\"\x15\x82\xd3\xe4\x93\x02\x0fb\x01*\x12\n" +
	"posmsinginB\x1eZ\x1cagdemoapi/api/pos_managementb\x06proto3"

var file_pos_management_pos_management_proto_goTypes = []any{
	(*common.CommonReq)(nil), // 0: common.CommonReq
	(*common.CommonRep)(nil), // 1: common.CommonRep
}
var file_pos_management_pos_management_proto_depIdxs = []int32{
	0, // 0: pos_management.PosManagement.SignIn:input_type -> common.CommonReq
	1, // 1: pos_management.PosManagement.SignIn:output_type -> common.CommonRep
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pos_management_pos_management_proto_init() }
func file_pos_management_pos_management_proto_init() {
	if File_pos_management_pos_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pos_management_pos_management_proto_rawDesc), len(file_pos_management_pos_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pos_management_pos_management_proto_goTypes,
		DependencyIndexes: file_pos_management_pos_management_proto_depIdxs,
	}.Build()
	File_pos_management_pos_management_proto = out.File
	file_pos_management_pos_management_proto_goTypes = nil
	file_pos_management_pos_management_proto_depIdxs = nil
}
