// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demoa/demoA.proto

package adpinit

import (
	demoa "agdemoA/internal/adpgen/kitex/demoa"
)

func init() {
	AddFxAdapterOpt(demoa.FxDemoAKitexModule)
}
