// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demoa/demoA.proto

package adpinit

import (
	demoa "agdemoA/internal/adpgen/hertz/demoa"
)

func init() {
	AddFxAdapterOpt(demoa.FxDemoAHertzModule)
}
