// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressc/stressc.proto

package cservice

import (
	hserver "ag-core/contribute/aghertz/server"
	stressc "ag_stress_c/api/stressc"
	"context"
	app "github.com/cloudwego/hertz/pkg/app"
	consts "github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Router_CService_EchoC_0_POST_Hertz
// @Name: EchoC
// @Method: POST
// @Path: echo/c
func Router_CService_EchoC_0_POST_Hertz(s stressc.CService) *hserver.Route {
	return &hserver.Route{
		HttpMethod:   "POST",
		RelativePath: "echo/c",
		Handlers:     append(make([]app.HandlerFunc, 0), _CService_EchoC_0_HTTP_Handler(s)),
	}
}

func _CService_EchoC_0_HTTP_Handler(s stressc.CService) func(ctx context.Context, c *app.RequestContext) {
	return func(ctx context.Context, c *app.RequestContext) {
		//var in = new(stressc.EchoCRequest)
		var in stressc.EchoCRequest
		// BindByContentType 当Method为GET时，会自动调用BindQuery，其他方法会调用对应Bind
		if err := c.BindByContentType(&in); err != nil {
			c.String(consts.StatusBadRequest, err.Error())
			return
		}

		resp, err := s.EchoC(ctx, &in)
		if err != nil {
			// TODO 增强异常处理
			c.String(consts.StatusInternalServerError, err.Error())
			return
		}

		// c.JSON 会自动将 Content-Type 设置为 application/json,
		c.JSON(consts.StatusOK, resp)
	}
}
