// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressc/stressc.proto

package cservice

import (
	hserver "ag-core/contribute/aghertz/server"
	fx "go.uber.org/fx"
)

var FxCServiceHertzModule = fx.Module("fx_CService_hertz",
	FxCService_EchoC_hertz_RegProvider,
)
var FxCService_EchoC_hertz_RegProvider = fx.Provide(
	hserver.NewFxServerRouteProvider(
		Router_CService_EchoC_0_POST_Hertz,
	),
)
