// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressa/stressa.proto

package aservice

import (
	akserver "ag-core/contribute/agkitex/server"
	stressa "ag_stress_a/api/stressa"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler stressa.AService, opts ...server.Option) server.Server {
	var options []server.Option
	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler stressa.AService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}

// Register_AService_KitexServer ag_kitex service register.

func Register_AService_KitexServer(srv stressa.AService) *akserver.AgKitexServiceRegistry {
	reg := akserver.NewAgKitexServiceRegistry(
		NewServiceInfo(),
		srv,
	)
	return reg
}
