// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressa/stressa.proto

package aservice

import (
	stressa "ag_stress_a/api/stressa"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var aServiceServiceMethods = map[string]kitex.MethodInfo{
	"echoA": kitex.NewMethodInfo(
		echoAHandler,
		newEchoAArgs,
		newEchoAResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	aServiceServiceInfo                = NewServiceInfo()
	aServiceServiceInfoForClient       = NewServiceInfoForClient()
	aServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return aServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return aServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return aServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "aService"
	handlerType := (*stressa.AService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range aServiceServiceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "stressa",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.14.1_by_aggen", // FIXME 模板生成时应该获取kitex版本
		Extra:           extra,
	}
	return svcInfo
}

func echoAHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(stressa.EchoARequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(stressa.AService).EchoA(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *EchoAArgs:
		success, err := handler.(stressa.AService).EchoA(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*EchoAResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newEchoAArgs() interface{} {
	return &EchoAArgs{}
}

func newEchoAResult() interface{} {
	return &EchoAResult{}
}

type EchoAArgs struct {
	Req *stressa.EchoARequest
}

func (p *EchoAArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *EchoAArgs) Unmarshal(in []byte) error {
	msg := new(stressa.EchoARequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var EchoAArgs_Req_DEFAULT *stressa.EchoARequest

func (p *EchoAArgs) GetReq() *stressa.EchoARequest {
	if !p.IsSetReq() {
		return EchoAArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *EchoAArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *EchoAArgs) GetFirstArgument() interface{} {
	return p.Req
}

type EchoAResult struct {
	Success *stressa.EchoAResponse
}

var EchoAResult_Success_DEFAULT *stressa.EchoAResponse

func (p *EchoAResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *EchoAResult) Unmarshal(in []byte) error {
	msg := new(stressa.EchoAResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *EchoAResult) GetSuccess() *stressa.EchoAResponse {
	if !p.IsSetSuccess() {
		return EchoAResult_Success_DEFAULT
	}
	return p.Success
}

func (p *EchoAResult) SetSuccess(x interface{}) {
	p.Success = x.(*stressa.EchoAResponse)
}

func (p *EchoAResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EchoAResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) EchoA(ctx context.Context, Req *stressa.EchoARequest) (r *stressa.EchoAResponse, err error) {
	var _args EchoAArgs
	_args.Req = Req
	var _result EchoAResult
	if err = p.c.Call(ctx, "echoA", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
