// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
//
// GenScope: module
// Versions:
//   - agserver: v0.0.1
//   - protoc: v6.33.1

package adpgen

import (
	adpinit "agdemoA/internal/adpgen/adpinit"
	fx "go.uber.org/fx"
)

// FxAdapterModule return adapter fx module
func FxAdapterModule() fx.Option {
	fxAdapterOpts := adpinit.GetFxAdapterOpt()
	return fx.Module("fx-adapter", fxAdapterOpts...)
}
