// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demob/demoB.proto

package demob

import (
	hserver "ag-core/contribute/aghertz/server"
	demob "agdemoB/api/demob"
	"context"
	app "github.com/cloudwego/hertz/pkg/app"
	consts "github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Router_Demob_Calldemob_0_POST_Hertz
// @Name: Calldemob
// @Method: POST
// @Path: calldemoB
func Router_Demob_Calldemob_0_POST_Hertz(s demob.Demob) *hserver.Route {
	return &hserver.Route{
		HttpMethod:   "POST",
		RelativePath: "calldemoB",
		Handlers:     append(make([]app.HandlerFunc, 0), _Demob_Calldemob_0_HTTP_Handler(s)),
	}
}

func _Demob_Calldemob_0_HTTP_Handler(s demob.Demob) func(ctx context.Context, c *app.RequestContext) {
	return func(ctx context.Context, c *app.RequestContext) {
		//var in = new(demob.BRequest)
		var in demob.BRequest
		// BindByContentType 当Method为GET时，会自动调用BindQuery，其他方法会调用对应Bind
		if err := c.BindByContentType(&in); err != nil {
			c.String(consts.StatusBadRequest, err.Error())
			return
		}

		resp, err := s.Calldemob(ctx, &in)
		if err != nil {
			// TODO 增强异常处理
			c.String(consts.StatusInternalServerError, err.Error())
			return
		}

		// c.JSON 会自动将 Content-Type 设置为 application/json,
		c.JSON(consts.StatusOK, resp)
	}
}
