// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demob/demoB.proto

package demob

import (
	agclient "ag-core/contribute/aghertz/aghertzclient"
	demob "agdemoB/api/demob"
	"context"
	"github.com/cloudwego/hertz/pkg/app/client"
	config "github.com/cloudwego/hertz/pkg/common/config"
)

// DemobHertzClient is the hertz client for Demob.
type DemobHertzClient interface {
	// Calldemob
	Calldemob(ctx context.Context, req *demob.BRequest, opts ...config.RequestOption) (resp *demob.BReply, err error)
}

// NewDemobHertzClient is the constructor for DemobHertzClient.
func NewDemobHertzClient(hc *client.Client, opts ...agclient.AgHertzClientOption) DemobHertzClient {
	client := &DemobHertzClientImpl{
		HertzBaseClient: agclient.NewHertzBaseClient(hc, opts...),
	}
	return client
}

// DemobHertzClientImpl is the hertz client impl for Demob.
type DemobHertzClientImpl struct {
	*agclient.HertzBaseClient
}

// Calldemob client impl Calldemob
func (c *DemobHertzClientImpl) Calldemob(ctx context.Context, req *demob.BRequest, opts ...config.RequestOption) (*demob.BReply, error) {
	var resp demob.BReply

	// 构建请求配置
	reqParam := &agclient.RequestParam{
		Method: "POST",
		Path:   "calldemoB",
	}
	rerr := c.DoRequest(ctx, reqParam, req, &resp, opts...)
	if rerr != nil {
		return nil, rerr
	}

	return &resp, nil
}
