// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demob/demoB.proto

package demob

import (
	hserver "ag-core/contribute/aghertz/server"
	fx "go.uber.org/fx"
)

var FxDemobHertzModule = fx.Module("fx_Demob_hertz",
	FxDemob_Calldemob_hertz_RegProvider,
)
var FxDemob_Calldemob_hertz_RegProvider = fx.Provide(
	hserver.NewFxServerRouteProvider(
		Router_Demob_Calldemob_0_POST_Hertz,
	),
)
