// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agservice: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressa/stressa.proto

package svcgen

import (
	ag_service "ag-core/ag/ag_service"
	stressa "ag_stress_a/api/stressa"
	service "ag_stress_a/internal/service"
	"context"
	"fmt"
	slog "log/slog"
)

// ServiceInfo interface level

var AServiceServiceInfo = ag_service.NewServiceInfo(
	"stressa",
	"AService",
	(*stressa.AService)(nil),
)

var AServiceEchoACallInfo = ag_service.NewCallInfo(
	AServiceServiceInfo,
	"EchoA",
	false,
	false,
)

var AServiceCallInfos = map[string]*ag_service.CallInfo{
	"EchoA": AServiceEchoACallInfo,
}

// AServiceProxy 服务代理
type AServiceProxy struct {
	ag_service.AgServiceProxyBase
	impl *service.AServiceImpl
}

// NewAServiceProxy 创建AServiceProxy
func NewAServiceProxy(
	impl *service.AServiceImpl,
	agServiceBuilder ag_service.AgServiceBuilder,
	mws []ag_service.MiddlewareProvider,
) (stressa.AService, error) {

	p := &AServiceProxy{
		impl: impl,
		AgServiceProxyBase: ag_service.NewAgServiceProxyBase(
			AServiceServiceInfo,
			AServiceCallInfos,
		),
	}

	for _, cif := range p.CallInfos {
		if cif.IsClientStreaming() || cif.IsServerStreaming() {
			slog.Warn("agServiceProxy buildskip streaming method", "call_name", cif.CallName)
			continue
		}

		// 根据方法信息构建Endpoints
		oriEndpoint, err := p.getOriginalHandler(cif)
		if err != nil {
			return nil, err
		}
		endpoint, err := agServiceBuilder.BuildEndpointChain(
			cif,
			mws,
			oriEndpoint,
		)
		if err != nil {
			return nil, err
		}
		// 注册endpoint
		p.RegisterEndpoint(cif.CallName(), endpoint)
	}

	return p, nil
}

// EchoA AServiceProxy proxy
func (p *AServiceProxy) EchoA(ctx context.Context, req *stressa.EchoARequest) (*stressa.EchoAResponse, error) {
	endpoint := p.GetEndpoint("EchoA")

	resp, err := endpoint(ctx, req)
	if err != nil {
		slog.Error("failed to handle request!", "method", "EchoA", "error", err)
		return nil, err
	}

	return resp.(*stressa.EchoAResponse), nil
}

// getOriginalHandler
func (p *AServiceProxy) getOriginalHandler(cif *ag_service.CallInfo) (ag_service.Endpoint, error) {
	switch cif.CallName() {
	case "EchoA":
		return func(ctx context.Context, req interface{}) (interface{}, error) {
			return p.impl.EchoA(ctx, req.(*stressa.EchoARequest))
		}, nil
	default:
		return nil, fmt.Errorf("handler for method %s not implemented", cif.CallName)
	}
}
