// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
//
// GenScope: package_group
// Versions:
//   - agservice: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressa/stressa.proto

package svcgen

import (
	ag_service "ag-core/ag/ag_service"
	stressa "ag_stress_a/api/stressa"
	service "ag_stress_a/internal/service"
	fx "go.uber.org/fx"
)

// FxInAServiceMiddleware servcie middleware inject params
type FxInAServiceMiddleware struct {
	fx.In

	AgServiceBuilder ag_service.AgServiceBuilder

	CustomMws []ag_service.MiddlewareProvider `group:"fx_aservice_service_middleware" ,optional:"true"`
}

// NewAServiceProxyWithFxIn create AService proxy with fx inject
func NewAServiceProxyWithFxIn(in FxInAServiceMiddleware, svc *service.AServiceImpl) (stressa.AService, error) {
	return NewAServiceProxy(svc, in.AgServiceBuilder, in.CustomMws)
}

func init() {
	AddFxServiceWithProxyOpt(
		fx.Provide(
			service.NewAServiceImpl, // constructor return impl
			NewAServiceProxyWithFxIn,
		),
	)
}
