// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demoa/demoA.proto

package demoa

import (
	akserver "ag-core/contribute/agkitex/server"
	fx "go.uber.org/fx"
)

// FxDemoAKitexModule fx module
var FxDemoAKitexModule = fx.Module("fx_DemoA_kitex",
	FxDemoAKitexRegProvider,
)

// FxDemoAKitexRegProvider fx provide
var FxDemoAKitexRegProvider = fx.Provide(

	akserver.NewFxAgKitexServiceRegistry(
		Register_DemoA_KitexServer,
	),
)
