// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demoa/demoA.proto

package demoa

import (
	demoa "agdemoA/api/demoa"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var demoAServiceMethods = map[string]kitex.MethodInfo{
	"calldemoa": kitex.NewMethodInfo(
		calldemoaHandler,
		newCalldemoaArgs,
		newCalldemoaResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	demoAServiceInfo                = NewServiceInfo()
	demoAServiceInfoForClient       = NewServiceInfoForClient()
	demoAServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return demoAServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return demoAServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return demoAServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "DemoA"
	handlerType := (*demoa.DemoA)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range demoAServiceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "demoa",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.14.1_by_aggen", // FIXME 模板生成时应该获取kitex版本
		Extra:           extra,
	}
	return svcInfo
}

func calldemoaHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(demoa.ARequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(demoa.DemoA).Calldemoa(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CalldemoaArgs:
		success, err := handler.(demoa.DemoA).Calldemoa(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CalldemoaResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCalldemoaArgs() interface{} {
	return &CalldemoaArgs{}
}

func newCalldemoaResult() interface{} {
	return &CalldemoaResult{}
}

type CalldemoaArgs struct {
	Req *demoa.ARequest
}

func (p *CalldemoaArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CalldemoaArgs) Unmarshal(in []byte) error {
	msg := new(demoa.ARequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CalldemoaArgs_Req_DEFAULT *demoa.ARequest

func (p *CalldemoaArgs) GetReq() *demoa.ARequest {
	if !p.IsSetReq() {
		return CalldemoaArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CalldemoaArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CalldemoaArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CalldemoaResult struct {
	Success *demoa.AReply
}

var CalldemoaResult_Success_DEFAULT *demoa.AReply

func (p *CalldemoaResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CalldemoaResult) Unmarshal(in []byte) error {
	msg := new(demoa.AReply)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CalldemoaResult) GetSuccess() *demoa.AReply {
	if !p.IsSetSuccess() {
		return CalldemoaResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CalldemoaResult) SetSuccess(x interface{}) {
	p.Success = x.(*demoa.AReply)
}

func (p *CalldemoaResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CalldemoaResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Calldemoa(ctx context.Context, Req *demoa.ARequest) (r *demoa.AReply, err error) {
	var _args CalldemoaArgs
	_args.Req = Req
	var _result CalldemoaResult
	if err = p.c.Call(ctx, "calldemoa", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
