// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demoa/demoA.proto

package demoa

import (
	akserver "ag-core/contribute/agkitex/server"
	demoa "agdemoA/api/demoa"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler demoa.DemoA, opts ...server.Option) server.Server {
	var options []server.Option
	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler demoa.DemoA, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}

// Register_DemoA_KitexServer ag_kitex service register.

func Register_DemoA_KitexServer(srv demoa.DemoA) *akserver.AgKitexServiceRegistry {
	reg := akserver.NewAgKitexServiceRegistry(
		NewServiceInfo(),
		srv,
	)
	return reg
}
