// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressb/stressb.proto

package bservice

import (
	hserver "ag-core/contribute/aghertz/server"
	stressb "ag_stress_b/api/stressb"
	"context"
	app "github.com/cloudwego/hertz/pkg/app"
	consts "github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Router_BService_EchoB_0_POST_Hertz
// @Name: EchoB
// @Method: POST
// @Path: echo/b
func Router_BService_EchoB_0_POST_Hertz(s stressb.BService) *hserver.Route {
	return &hserver.Route{
		HttpMethod:   "POST",
		RelativePath: "echo/b",
		Handlers:     append(make([]app.HandlerFunc, 0), _BService_EchoB_0_HTTP_Handler(s)),
	}
}

func _BService_EchoB_0_HTTP_Handler(s stressb.BService) func(ctx context.Context, c *app.RequestContext) {
	return func(ctx context.Context, c *app.RequestContext) {
		//var in = new(stressb.EchoBRequest)
		var in stressb.EchoBRequest
		// BindByContentType 当Method为GET时，会自动调用BindQuery，其他方法会调用对应Bind
		if err := c.BindByContentType(&in); err != nil {
			c.String(consts.StatusBadRequest, err.Error())
			return
		}

		resp, err := s.EchoB(ctx, &in)
		if err != nil {
			// TODO 增强异常处理
			c.String(consts.StatusInternalServerError, err.Error())
			return
		}

		// c.JSON 会自动将 Content-Type 设置为 application/json,
		c.JSON(consts.StatusOK, resp)
	}
}
