// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressb/stressb.proto

package bservice

import (
	hserver "ag-core/contribute/aghertz/server"
	fx "go.uber.org/fx"
)

var FxBServiceHertzModule = fx.Module("fx_BService_hertz",
	FxBService_EchoB_hertz_RegProvider,
)
var FxBService_EchoB_hertz_RegProvider = fx.Provide(
	hserver.NewFxServerRouteProvider(
		Router_BService_EchoB_0_POST_Hertz,
	),
)
