// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressc/stressc.proto

package cservice

import (
	agclient "ag-core/contribute/aghertz/aghertzclient"
	stressc "ag_stress_c/api/stressc"
	"context"
	"github.com/cloudwego/hertz/pkg/app/client"
	config "github.com/cloudwego/hertz/pkg/common/config"
)

// CServiceHertzClient is the hertz client for CService.
type CServiceHertzClient interface {
	// EchoC
	EchoC(ctx context.Context, req *stressc.EchoCRequest, opts ...config.RequestOption) (resp *stressc.EchoCResponse, err error)
}

// NewCServiceHertzClient is the constructor for CServiceHertzClient.
func NewCServiceHertzClient(hc *client.Client, opts ...agclient.AgHertzClientOption) CServiceHertzClient {
	client := &CServiceHertzClientImpl{
		HertzBaseClient: agclient.NewHertzBaseClient(hc, opts...),
	}
	return client
}

// CServiceHertzClientImpl is the hertz client impl for CService.
type CServiceHertzClientImpl struct {
	*agclient.HertzBaseClient
}

// EchoC client impl EchoC
func (c *CServiceHertzClientImpl) EchoC(ctx context.Context, req *stressc.EchoCRequest, opts ...config.RequestOption) (*stressc.EchoCResponse, error) {
	var resp stressc.EchoCResponse

	// 构建请求配置
	reqParam := &agclient.RequestParam{
		Method: "POST",
		Path:   "echo/c",
	}
	rerr := c.DoRequest(ctx, reqParam, req, &resp, opts...)
	if rerr != nil {
		return nil, rerr
	}

	return &resp, nil
}
