// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agservice: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demob/demoB.proto

package svchzw

import (
	smw "ag-core/ag/ag_service"
	demob "agdemoB/api/demob"
	service "agdemoB/internal/service"
	"context"
	"fmt"
	slog "log/slog"
)

// DemobProxy 服务代理
type DemobProxy struct {
	impl        *service.DemobImpl
	endpoints   map[string]smw.Endpoint
	serviceInfo smw.ServiceInfo
	methodInfos map[string]smw.CallInfo
}

// NewDemobProxy 创建DemobProxy
func NewDemobProxy(service *service.DemobImpl, mws []smw.MiddlewareProvider) demob.Demob {
	sinfo := smw.ServiceInfo{
		PackageName: "api.demob",
		ServiceName: "demob",
	}

	proxy := &DemobProxy{
		impl:        service,
		endpoints:   make(map[string]smw.Endpoint),
		serviceInfo: sinfo,
	}

	// 注册处理链
	// proxy.handlers["Calldemob"] = smw.RegisterHandler("Calldemob", mws, func(ctx context.Context, req interface{}) (interface{}, error) {
	// 	return proxy.impl.Calldemob(ctx, req.(*demob.BRequest))
	// })

	// proxy.endpoints["Calldemob"] = smw.BuilderEndpointChain(
	// 	// TODO 方法级别的信息，怎么设置
	// 	sinfo, mws,
	// 	func(ctx context.Context, req interface{}) (interface{}, error) {
	// 		return proxy.impl.Calldemob(ctx, req.(*demob.BRequest))
	// 	},
	// )

	return proxy
}

// Hello TODO:DESCRIBE
func (c *DemobProxy) Hello(ctx context.Context, req *demob.BRequest) (*demob.BReply, error) {
	var resp *demob.BReply
	resp = &demob.BReply{}
	// TODO 添加业务处理逻辑

	return resp, nil
}

// Calldemob DemobProxy proxy
func (p *DemobProxy) Calldemob(ctx context.Context, req *demob.BRequest) (*demob.BReply, error) {

	methodName := "Calldemob"
	handler, ok := p.endpoints[methodName]
	if !ok {
		slog.Error("endpoint not found!", "method", methodName)
		return nil, fmt.Errorf("endpoint not found!")
	}

	res, err := handler(ctx, req)
	if err != nil {
		slog.Error("failed to handle request!", "method", methodName, "error", err)
		return nil, err
	}

	return res.(*demob.BReply), nil
}

// // ClientSideStreaming TODO:DESCRIBE
// // ClientStreaming
// func (p *DemobProxy) ClientSideStreaming(stream demob.Demob_ClientSideStreamingServer) error {
// 	// TODO
// 	return nil
// }

// // ServerSideStreaming TODO:DESCRIBE
// // ServerStreaming
// func (p *DemobProxy) ServerSideStreaming(req *demob.BRequest, stream demob.Demob_ServerSideStreamingServer) error {
// 	// TODO
// 	return nil
// }

// // BidiSideStreaming TODO:DESCRIBE
// // ClientStreaming and ServerStreaming
// func (p *DemobProxy) BidiSideStreaming(stream demob.Demob_BidiSideStreamingServer) error {
// 	// TODO
// 	return nil
// }
