// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
//
// GenScope: package_group
// Versions:
//   - agservice: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demob/demoB.proto

package svchzw

import (
	ag_service "ag-core/ag/ag_service"
	smw "ag-core/ag/ag_service"
	demob "agdemoB/api/demob"
	service "agdemoB/internal/service"

	fx "go.uber.org/fx"
)

// var FxdemobServiceProxyModule = fx.Module("fx-demob-service-proxy",
// 	fx.Provide(
// 		NewDemobProxyWithFxIn,
// 	),
// )

// FxInDemobMiddleware servcie middleware inject params
type FxInDemobMiddleware struct {
	fx.In

	AgServiceBuilder ag_service.AgServiceBuilder
	// smw.BaseFxMiddlewareParams
	// smw.BaseFxServiceMiddlewareParams
	CustomMws []smw.MiddlewareProvider `group:"fx_demob_service_middleware" ,optional:"true"`
}

// NewDemobProxyWithFxIn create Demob proxy with fx inject
func NewDemobProxyWithFxIn(in FxInDemobMiddleware, svc *service.DemobImpl) (demob.Demob, error) {
	// return NewDemobProxy(svc, append(in.GlobalMws, in.CustomMws...))
	// return NewDemobProxy_hzw(svc, in.agService, append(in.GlobalMws, in.CustomMws...))
	return NewDemobProxy_hzw(svc, in.AgServiceBuilder, in.CustomMws)
}

func init() {
	AddFxServiceWithProxyOpt(
		fx.Provide(
			// service.NewDemobImpl, // constructor return impl
			// NewDemobProxyWithFxIn,

			HzwCIFOptFx,
			HzwMWFx,
		),
	)
}
