// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
//
// GenScope: module
// Versions:
//   - agservice: v0.0.1
//   - protoc: v6.33.1

package svchzw

import (
	"sync"

	fx "go.uber.org/fx"
)

var (
	_lock2                 sync.Mutex
	fxServiceWithProxyOpts []fx.Option
)

// FxServiceWithProxyModule return service fx module with service proxy
func FxServiceWithProxyModule() fx.Option {
	_lock2.Lock()
	defer _lock2.Unlock()
	return fx.Module("fx-service-with-proxy2", fxServiceWithProxyOpts...)
}

// AddFxServiceWithProxyOpt add fx service option with proxy.
func AddFxServiceWithProxyOpt(opt fx.Option) {
	_lock2.Lock()
	defer _lock2.Unlock()
	if fxServiceWithProxyOpts == nil {
		fxServiceWithProxyOpts = []fx.Option{}
	}
	fxServiceWithProxyOpts = append(fxServiceWithProxyOpts, opt)
}
