// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressc/stressc.proto

package adpinit

import (
	cservice "ag_stress_c/internal/adpgen/kitex/cservice"
)

func init() {
	AddFxAdapterOpt(cservice.FxCServiceKitexModule)
}
