// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressc/stressc.proto

package adpinit

import (
	cservice "ag_stress_c/internal/adpgen/hertz/cservice"
)

func init() {
	AddFxAdapterOpt(cservice.FxCServiceHertzModule)
}
