// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
//
// GenScope: package_group
// Versions:
//   - agserver: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - logs/logapi.proto

package logs

import (
	"context"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
)

// LogServer defines the server interface for the LogServer service.
type LogServer interface {
	BatchLog(context.Context, *BatchLogRequest) (*BatchLogResponse, error)
	StreamLog(stream LogServer_StreamLogServer) (err error)
}

// LogServer_StreamLogServer
type LogServer_StreamLogServer interface {
	streaming.Stream
	Recv() (*BatchLogRequest, error)
	SendAndClose(*BatchLogResponse) error
}
