// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: logs/logapi.proto

package logs

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 压缩方式
type CompressionType int32

const (
	CompressionType_None   CompressionType = 0
	CompressionType_Gzip   CompressionType = 1
	CompressionType_Snappy CompressionType = 2
	CompressionType_Lz4    CompressionType = 3
	CompressionType_Zstd   CompressionType = 4
)

// Enum value maps for CompressionType.
var (
	CompressionType_name = map[int32]string{
		0: "None",
		1: "Gzip",
		2: "Snappy",
		3: "Lz4",
		4: "Zstd",
	}
	CompressionType_value = map[string]int32{
		"None":   0,
		"Gzip":   1,
		"Snappy": 2,
		"Lz4":    3,
		"Zstd":   4,
	}
)

func (x CompressionType) Enum() *CompressionType {
	p := new(CompressionType)
	*p = x
	return p
}

func (x CompressionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompressionType) Descriptor() protoreflect.EnumDescriptor {
	return file_logs_logapi_proto_enumTypes[0].Descriptor()
}

func (CompressionType) Type() protoreflect.EnumType {
	return &file_logs_logapi_proto_enumTypes[0]
}

func (x CompressionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompressionType.Descriptor instead.
func (CompressionType) EnumDescriptor() ([]byte, []int) {
	return file_logs_logapi_proto_rawDescGZIP(), []int{0}
}

type BatchMetadata struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Host        string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	HostName    string                 `protobuf:"bytes,2,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"` // FIXME k8s中如何定位到主机、pod、容器
	ProcessId   int32                  `protobuf:"varint,3,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	ProcessName string                 `protobuf:"bytes,4,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	// string app_id = 5;
	Exts          map[string]string `protobuf:"bytes,6,rep,name=exts,proto3" json:"exts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchMetadata) Reset() {
	*x = BatchMetadata{}
	mi := &file_logs_logapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMetadata) ProtoMessage() {}

func (x *BatchMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_logs_logapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMetadata.ProtoReflect.Descriptor instead.
func (*BatchMetadata) Descriptor() ([]byte, []int) {
	return file_logs_logapi_proto_rawDescGZIP(), []int{0}
}

func (x *BatchMetadata) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *BatchMetadata) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *BatchMetadata) GetProcessId() int32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *BatchMetadata) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *BatchMetadata) GetExts() map[string]string {
	if x != nil {
		return x.Exts
	}
	return nil
}

type LogEntry struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level     string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message   string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	TraceId   string                 `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId    string                 `protobuf:"bytes,5,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	Type      string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"` // RPC、trade、... 自定义的
	// 单条日志私有字段（可选，不重复传输共享信息）
	ThreadId      string            `protobuf:"bytes,7,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	ThreadName    string            `protobuf:"bytes,8,opt,name=thread_name,json=threadName,proto3" json:"thread_name,omitempty"`
	OrgNo         string            `protobuf:"bytes,9,opt,name=org_no,json=orgNo,proto3" json:"org_no,omitempty"`
	Attrs         map[string]string `protobuf:"bytes,10,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_logs_logapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_logs_logapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_logs_logapi_proto_rawDescGZIP(), []int{1}
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *LogEntry) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *LogEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LogEntry) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *LogEntry) GetThreadName() string {
	if x != nil {
		return x.ThreadName
	}
	return ""
}

func (x *LogEntry) GetOrgNo() string {
	if x != nil {
		return x.OrgNo
	}
	return ""
}

func (x *LogEntry) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

type BatchLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchMeta     *BatchMetadata         `protobuf:"bytes,1,opt,name=batch_meta,json=batchMeta,proto3" json:"batch_meta,omitempty"`
	Logs          []*LogEntry            `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"` // logs进行压缩
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchLogRequest) Reset() {
	*x = BatchLogRequest{}
	mi := &file_logs_logapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchLogRequest) ProtoMessage() {}

func (x *BatchLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logs_logapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchLogRequest.ProtoReflect.Descriptor instead.
func (*BatchLogRequest) Descriptor() ([]byte, []int) {
	return file_logs_logapi_proto_rawDescGZIP(), []int{2}
}

func (x *BatchLogRequest) GetBatchMeta() *BatchMetadata {
	if x != nil {
		return x.BatchMeta
	}
	return nil
}

func (x *BatchLogRequest) GetLogs() []*LogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

// 批量响应
type BatchLogResponse struct {
	state           protoimpl.MessageState             `protogen:"open.v1"`
	Code            int32                              `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message         string                             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId       string                             `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AcceptedCount   int32                              `protobuf:"varint,4,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	RejectedCount   int32                              `protobuf:"varint,5,opt,name=rejected_count,json=rejectedCount,proto3" json:"rejected_count,omitempty"`
	RejectedDetails []*BatchLogResponse_RejectedDetail `protobuf:"bytes,6,rep,name=rejected_details,json=rejectedDetails,proto3" json:"rejected_details,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchLogResponse) Reset() {
	*x = BatchLogResponse{}
	mi := &file_logs_logapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchLogResponse) ProtoMessage() {}

func (x *BatchLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logs_logapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchLogResponse.ProtoReflect.Descriptor instead.
func (*BatchLogResponse) Descriptor() ([]byte, []int) {
	return file_logs_logapi_proto_rawDescGZIP(), []int{3}
}

func (x *BatchLogResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BatchLogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BatchLogResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BatchLogResponse) GetAcceptedCount() int32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

func (x *BatchLogResponse) GetRejectedCount() int32 {
	if x != nil {
		return x.RejectedCount
	}
	return 0
}

func (x *BatchLogResponse) GetRejectedDetails() []*BatchLogResponse_RejectedDetail {
	if x != nil {
		return x.RejectedDetails
	}
	return nil
}

type BatchLogResponse_RejectedDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchLogResponse_RejectedDetail) Reset() {
	*x = BatchLogResponse_RejectedDetail{}
	mi := &file_logs_logapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchLogResponse_RejectedDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchLogResponse_RejectedDetail) ProtoMessage() {}

func (x *BatchLogResponse_RejectedDetail) ProtoReflect() protoreflect.Message {
	mi := &file_logs_logapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchLogResponse_RejectedDetail.ProtoReflect.Descriptor instead.
func (*BatchLogResponse_RejectedDetail) Descriptor() ([]byte, []int) {
	return file_logs_logapi_proto_rawDescGZIP(), []int{3, 0}
}

func (x *BatchLogResponse_RejectedDetail) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BatchLogResponse_RejectedDetail) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_logs_logapi_proto protoreflect.FileDescriptor

const file_logs_logapi_proto_rawDesc = "" +
	"\n" +
	"\x11logs/logapi.proto\x12\bapi.logs\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a google/protobuf/descriptor.proto\"\xf2\x01\n" +
	"\rBatchMetadata\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x1b\n" +
	"\thost_name\x18\x02 \x01(\tR\bhostName\x12\x1d\n" +
	"\n" +
	"process_id\x18\x03 \x01(\x05R\tprocessId\x12!\n" +
	"\fprocess_name\x18\x04 \x01(\tR\vprocessName\x125\n" +
	"\x04exts\x18\x06 \x03(\v2!.api.logs.BatchMetadata.ExtsEntryR\x04exts\x1a7\n" +
	"\tExtsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe4\x02\n" +
	"\bLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x05 \x01(\tR\x06spanId\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x1b\n" +
	"\tthread_id\x18\a \x01(\tR\bthreadId\x12\x1f\n" +
	"\vthread_name\x18\b \x01(\tR\n" +
	"threadName\x12\x15\n" +
	"\x06org_no\x18\t \x01(\tR\x05orgNo\x123\n" +
	"\x05attrs\x18\n" +
	" \x03(\v2\x1d.api.logs.LogEntry.AttrsEntryR\x05attrs\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"q\n" +
	"\x0fBatchLogRequest\x126\n" +
	"\n" +
	"batch_meta\x18\x01 \x01(\v2\x17.api.logs.BatchMetadataR\tbatchMeta\x12&\n" +
	"\x04logs\x18\x02 \x03(\v2\x12.api.logs.LogEntryR\x04logs\"\xc3\x02\n" +
	"\x10BatchLogResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12%\n" +
	"\x0eaccepted_count\x18\x04 \x01(\x05R\racceptedCount\x12%\n" +
	"\x0erejected_count\x18\x05 \x01(\x05R\rrejectedCount\x12T\n" +
	"\x10rejected_details\x18\x06 \x03(\v2).api.logs.BatchLogResponse.RejectedDetailR\x0frejectedDetails\x1a>\n" +
	"\x0eRejectedDetail\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason*D\n" +
	"\x0fCompressionType\x12\b\n" +
	"\x04None\x10\x00\x12\b\n" +
	"\x04Gzip\x10\x01\x12\n" +
	"\n" +
	"\x06Snappy\x10\x02\x12\a\n" +
	"\x03Lz4\x10\x03\x12\b\n" +
	"\x04Zstd\x10\x042\xb4\x01\n" +
	"\tLogServer\x12_\n" +
	"\bBatchLog\x12\x19.api.logs.BatchLogRequest\x1a\x1a.api.logs.BatchLogResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*b\x01*\"\x0e/v1/logs/batch\x12F\n" +
	"\tStreamLog\x12\x19.api.logs.BatchLogRequest\x1a\x1a.api.logs.BatchLogResponse\"\x00(\x01B*\n" +
	"\bapi.logsB\tLogServerP\x01Z\x11xxx/api/logs;logsb\x06proto3"

var (
	file_logs_logapi_proto_rawDescOnce sync.Once
	file_logs_logapi_proto_rawDescData []byte
)

func file_logs_logapi_proto_rawDescGZIP() []byte {
	file_logs_logapi_proto_rawDescOnce.Do(func() {
		file_logs_logapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logs_logapi_proto_rawDesc), len(file_logs_logapi_proto_rawDesc)))
	})
	return file_logs_logapi_proto_rawDescData
}

var file_logs_logapi_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_logs_logapi_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_logs_logapi_proto_goTypes = []any{
	(CompressionType)(0),                    // 0: api.logs.CompressionType
	(*BatchMetadata)(nil),                   // 1: api.logs.BatchMetadata
	(*LogEntry)(nil),                        // 2: api.logs.LogEntry
	(*BatchLogRequest)(nil),                 // 3: api.logs.BatchLogRequest
	(*BatchLogResponse)(nil),                // 4: api.logs.BatchLogResponse
	nil,                                     // 5: api.logs.BatchMetadata.ExtsEntry
	nil,                                     // 6: api.logs.LogEntry.AttrsEntry
	(*BatchLogResponse_RejectedDetail)(nil), // 7: api.logs.BatchLogResponse.RejectedDetail
}
var file_logs_logapi_proto_depIdxs = []int32{
	5, // 0: api.logs.BatchMetadata.exts:type_name -> api.logs.BatchMetadata.ExtsEntry
	6, // 1: api.logs.LogEntry.attrs:type_name -> api.logs.LogEntry.AttrsEntry
	1, // 2: api.logs.BatchLogRequest.batch_meta:type_name -> api.logs.BatchMetadata
	2, // 3: api.logs.BatchLogRequest.logs:type_name -> api.logs.LogEntry
	7, // 4: api.logs.BatchLogResponse.rejected_details:type_name -> api.logs.BatchLogResponse.RejectedDetail
	3, // 5: api.logs.LogServer.BatchLog:input_type -> api.logs.BatchLogRequest
	3, // 6: api.logs.LogServer.StreamLog:input_type -> api.logs.BatchLogRequest
	4, // 7: api.logs.LogServer.BatchLog:output_type -> api.logs.BatchLogResponse
	4, // 8: api.logs.LogServer.StreamLog:output_type -> api.logs.BatchLogResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_logs_logapi_proto_init() }
func file_logs_logapi_proto_init() {
	if File_logs_logapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logs_logapi_proto_rawDesc), len(file_logs_logapi_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logs_logapi_proto_goTypes,
		DependencyIndexes: file_logs_logapi_proto_depIdxs,
		EnumInfos:         file_logs_logapi_proto_enumTypes,
		MessageInfos:      file_logs_logapi_proto_msgTypes,
	}.Build()
	File_logs_logapi_proto = out.File
	file_logs_logapi_proto_goTypes = nil
	file_logs_logapi_proto_depIdxs = nil
}
