// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - hello/hello.proto

package adpinit

import (
	hello "agdemoC/internal/adpgen/kitex/hello"
)

func init() {
	AddFxAdapterOpt(hello.FxHelloKitexModule)
}
