// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - hello/hello.proto

package adpinit

import (
	hello "agdemoC/internal/adpgen/hertz/hello"
)

func init() {
	AddFxAdapterOpt(hello.FxHelloHertzModule)
}
