// Code generated by aic-generate, DO NOT EDIT
// Code generated by aic-generate, DO NOT EDIT
// Code generated by aic-generate, DO NOT EDIT

/* Drop Tables */
DROP TABLE IF EXISTS student;


CREATE TABLE student
(
	ID bigint NOT NULL AUTO_INCREMENT COMMENT '' ,
	STUNO bigint NOT NULL  COMMENT '' ,
	NAME varchar   COMMENT '' ,
	AGE int NOT NULL  COMMENT '年龄' ,
	VERSION bigint   COMMENT '' ,
	FCT datetime   COMMENT '创建时间' ,
	LCT datetime   COMMENT '最后更新时间' 
    
	PRIMARY KEY (id)
) ;


/* Create Indexes */
CREATE INDEX INDEX_NAME_AGE USING General ON student (name,age);
CREATE UNIQUE INDEX STUNO_UNIUQE_1 USING Unique ON student (stuno);