// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - hello/hello.proto

package hello

import (
	akserver "ag-core/contribute/agkitex/server"
	hello "agdemoC/api/hello"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler hello.Hello, opts ...server.Option) server.Server {
	var options []server.Option
	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler hello.Hello, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}

// Register_Hello_KitexServer ag_kitex service register.

func Register_Hello_KitexServer(srv hello.Hello) *akserver.AgKitexServiceRegistry {
	reg := akserver.NewAgKitexServiceRegistry(
		NewServiceInfo(),
		srv,
	)
	return reg
}
