// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - hello/hello.proto

package hello

import (
	akserver "ag-core/contribute/agkitex/server"
	fx "go.uber.org/fx"
)

// FxHelloKitexModule fx module
var FxHelloKitexModule = fx.Module("fx_Hello_kitex",
	FxHelloKitexRegProvider,
)

// FxHelloKitexRegProvider fx provide
var FxHelloKitexRegProvider = fx.Provide(

	akserver.NewFxAgKitexServiceRegistry(
		Register_Hello_KitexServer,
	),
)
