// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - hello/hello.proto

package hello

import (
	hello "agdemoC/api/hello"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var helloServiceMethods = map[string]kitex.MethodInfo{
	"pinghello": kitex.NewMethodInfo(
		pinghelloHandler,
		newPinghelloArgs,
		newPinghelloResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	helloServiceInfo                = NewServiceInfo()
	helloServiceInfoForClient       = NewServiceInfoForClient()
	helloServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return helloServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return helloServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return helloServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "hello"
	handlerType := (*hello.Hello)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range helloServiceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "api.hello",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.14.1_by_aggen", // FIXME 模板生成时应该获取kitex版本
		Extra:           extra,
	}
	return svcInfo
}

func pinghelloHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(hello.HelloRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(hello.Hello).Pinghello(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *PinghelloArgs:
		success, err := handler.(hello.Hello).Pinghello(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*PinghelloResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newPinghelloArgs() interface{} {
	return &PinghelloArgs{}
}

func newPinghelloResult() interface{} {
	return &PinghelloResult{}
}

type PinghelloArgs struct {
	Req *hello.HelloRequest
}

func (p *PinghelloArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *PinghelloArgs) Unmarshal(in []byte) error {
	msg := new(hello.HelloRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var PinghelloArgs_Req_DEFAULT *hello.HelloRequest

func (p *PinghelloArgs) GetReq() *hello.HelloRequest {
	if !p.IsSetReq() {
		return PinghelloArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *PinghelloArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PinghelloArgs) GetFirstArgument() interface{} {
	return p.Req
}

type PinghelloResult struct {
	Success *hello.HelloReply
}

var PinghelloResult_Success_DEFAULT *hello.HelloReply

func (p *PinghelloResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *PinghelloResult) Unmarshal(in []byte) error {
	msg := new(hello.HelloReply)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *PinghelloResult) GetSuccess() *hello.HelloReply {
	if !p.IsSetSuccess() {
		return PinghelloResult_Success_DEFAULT
	}
	return p.Success
}

func (p *PinghelloResult) SetSuccess(x interface{}) {
	p.Success = x.(*hello.HelloReply)
}

func (p *PinghelloResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PinghelloResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Pinghello(ctx context.Context, Req *hello.HelloRequest) (r *hello.HelloReply, err error) {
	var _args PinghelloArgs
	_args.Req = Req
	var _result PinghelloResult
	if err = p.c.Call(ctx, "pinghello", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
