// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
//
// GenScope: package_group
// Versions:
//   - agserver: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressa/stressa.proto

package stressa

import (
	"context"
)

// AService defines the server interface for the AService service.
type AService interface {
	EchoA(context.Context, *EchoARequest) (*EchoAResponse, error)
}
