// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: stressa/stressa.proto

package stressa

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoARequest) Reset() {
	*x = EchoARequest{}
	mi := &file_stressa_stressa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoARequest) ProtoMessage() {}

func (x *EchoARequest) ProtoReflect() protoreflect.Message {
	mi := &file_stressa_stressa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoARequest.ProtoReflect.Descriptor instead.
func (*EchoARequest) Descriptor() ([]byte, []int) {
	return file_stressa_stressa_proto_rawDescGZIP(), []int{0}
}

func (x *EchoARequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EchoAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoAResponse) Reset() {
	*x = EchoAResponse{}
	mi := &file_stressa_stressa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoAResponse) ProtoMessage() {}

func (x *EchoAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stressa_stressa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoAResponse.ProtoReflect.Descriptor instead.
func (*EchoAResponse) Descriptor() ([]byte, []int) {
	return file_stressa_stressa_proto_rawDescGZIP(), []int{1}
}

func (x *EchoAResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_stressa_stressa_proto protoreflect.FileDescriptor

const file_stressa_stressa_proto_rawDesc = "" +
	"\n" +
	"\x15stressa/stressa.proto\x12\astressa\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/descriptor.proto\"\"\n" +
	"\fEchoARequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"!\n" +
	"\rEchoAResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2X\n" +
	"\baService\x12L\n" +
	"\x05echoA\x12\x15.stressa.EchoARequest\x1a\x16.stressa.EchoAResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*b\x01*\"\x06echo/aB\x19Z\x17ag_stress_a/api/stressab\x06proto3"

var (
	file_stressa_stressa_proto_rawDescOnce sync.Once
	file_stressa_stressa_proto_rawDescData []byte
)

func file_stressa_stressa_proto_rawDescGZIP() []byte {
	file_stressa_stressa_proto_rawDescOnce.Do(func() {
		file_stressa_stressa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stressa_stressa_proto_rawDesc), len(file_stressa_stressa_proto_rawDesc)))
	})
	return file_stressa_stressa_proto_rawDescData
}

var file_stressa_stressa_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stressa_stressa_proto_goTypes = []any{
	(*EchoARequest)(nil),  // 0: stressa.EchoARequest
	(*EchoAResponse)(nil), // 1: stressa.EchoAResponse
}
var file_stressa_stressa_proto_depIdxs = []int32{
	0, // 0: stressa.aService.echoA:input_type -> stressa.EchoARequest
	1, // 1: stressa.aService.echoA:output_type -> stressa.EchoAResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stressa_stressa_proto_init() }
func file_stressa_stressa_proto_init() {
	if File_stressa_stressa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stressa_stressa_proto_rawDesc), len(file_stressa_stressa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stressa_stressa_proto_goTypes,
		DependencyIndexes: file_stressa_stressa_proto_depIdxs,
		MessageInfos:      file_stressa_stressa_proto_msgTypes,
	}.Build()
	File_stressa_stressa_proto = out.File
	file_stressa_stressa_proto_goTypes = nil
	file_stressa_stressa_proto_depIdxs = nil
}
