// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agservice: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressc/stressc.proto

package svcgen

import (
	ag_service "ag-core/ag/ag_service"
	stressc "ag_stress_c/api/stressc"
	service "ag_stress_c/internal/service"
	"context"
	"fmt"
	slog "log/slog"
)

// ServiceInfo interface level

var CServiceServiceInfo = ag_service.NewServiceInfo(
	"stressc",
	"CService",
	(*stressc.CService)(nil),
)

var CServiceEchoCCallInfo = ag_service.NewCallInfo(
	CServiceServiceInfo,
	"EchoC",
	false,
	false,
)

var CServiceCallInfos = map[string]*ag_service.CallInfo{
	"EchoC": CServiceEchoCCallInfo,
}

// CServiceProxy 服务代理
type CServiceProxy struct {
	ag_service.AgServiceProxyBase
	impl *service.CServiceImpl
}

// NewCServiceProxy 创建CServiceProxy
func NewCServiceProxy(
	impl *service.CServiceImpl,
	agServiceBuilder ag_service.AgServiceBuilder,
	mws []ag_service.MiddlewareProvider,
) (stressc.CService, error) {

	p := &CServiceProxy{
		impl: impl,
		AgServiceProxyBase: ag_service.NewAgServiceProxyBase(
			CServiceServiceInfo,
			CServiceCallInfos,
		),
	}

	for _, cif := range p.CallInfos {
		if cif.IsClientStreaming() || cif.IsServerStreaming() {
			slog.Warn("agServiceProxy buildskip streaming method", "call_name", cif.CallName)
			continue
		}

		// 根据方法信息构建Endpoints
		oriEndpoint, err := p.getOriginalHandler(cif)
		if err != nil {
			return nil, err
		}
		endpoint, err := agServiceBuilder.BuildEndpointChain(
			cif,
			mws,
			oriEndpoint,
		)
		if err != nil {
			return nil, err
		}
		// 注册endpoint
		p.RegisterEndpoint(cif.CallName(), endpoint)
	}

	return p, nil
}

// EchoC CServiceProxy proxy
func (p *CServiceProxy) EchoC(ctx context.Context, req *stressc.EchoCRequest) (*stressc.EchoCResponse, error) {
	endpoint := p.GetEndpoint("EchoC")

	resp, err := endpoint(ctx, req)
	if err != nil {
		slog.Error("failed to handle request!", "method", "EchoC", "error", err)
		return nil, err
	}

	return resp.(*stressc.EchoCResponse), nil
}

// getOriginalHandler
func (p *CServiceProxy) getOriginalHandler(cif *ag_service.CallInfo) (ag_service.Endpoint, error) {
	switch cif.CallName() {
	case "EchoC":
		return func(ctx context.Context, req interface{}) (interface{}, error) {
			return p.impl.EchoC(ctx, req.(*stressc.EchoCRequest))
		}, nil
	default:
		return nil, fmt.Errorf("handler for method %s not implemented", cif.CallName)
	}
}
