// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
//
// GenScope: package_group
// Versions:
//   - agservice: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressc/stressc.proto

package svcgen

import (
	ag_service "ag-core/ag/ag_service"
	stressc "ag_stress_c/api/stressc"
	service "ag_stress_c/internal/service"
	fx "go.uber.org/fx"
)

// FxInCServiceMiddleware servcie middleware inject params
type FxInCServiceMiddleware struct {
	fx.In

	AgServiceBuilder ag_service.AgServiceBuilder

	CustomMws []ag_service.MiddlewareProvider `group:"fx_cservice_service_middleware" ,optional:"true"`
}

// NewCServiceProxyWithFxIn create CService proxy with fx inject
func NewCServiceProxyWithFxIn(in FxInCServiceMiddleware, svc *service.CServiceImpl) (stressc.CService, error) {
	return NewCServiceProxy(svc, in.AgServiceBuilder, in.CustomMws)
}

func init() {
	AddFxServiceWithProxyOpt(
		fx.Provide(
			service.NewCServiceImpl, // constructor return impl
			NewCServiceProxyWithFxIn,
		),
	)
}
