// Code generated by aic-generate, DO NOT EDIT
// Code generated by aic-generate, DO NOT EDIT
// Code generated by aic-generate, DO NOT EDIT

package daohzw

// import (
// 	db "ag-core/contribute/agdb/gormdb"
// 	"agdemoB/internal/repository/dao"
// 	"agdemoB/internal/repository/daohzw/daoopt"
// 	"agdemoB/internal/repository/model"
// 	"context"
// 	"errors"

// 	"gorm.io/gorm"
// )

// var StudentNamingSqlMap = map[string]string{}

// // type IStudentDao interface {
// // 	InsertOne(ctx context.Context, arg *model.Student) (int64, error)
// // 	InsertOneIgnoreZeroVal(ctx context.Context, arg *model.Student) (int64, error)
// // 	FindByPrimaryKey(ctx context.Context, Id int64) (*model.Student, error)
// // 	UpdateByPrimaryKey(ctx context.Context, arg *model.Student) (int64, error)
// // 	UpdateByPriIngoreNullCols(ctx context.Context, arg *model.Student) (int64, error)
// // 	DeleteByPrimaryKey(ctx context.Context, Id int64) (int64, error)
// // 	FindByNameAge(ctx context.Context, Name string, Age int) ([]model.Student, error)
// // 	FindByStuno(ctx context.Context, Stuno int64) (*model.Student, error)
// // 	UpdateByStuno(ctx context.Context, Stuno int64, arg *model.Student) (int64, error)
// // 	DeleteByStuno(ctx context.Context, Stuno int64) (int64, error)

// // 	// 查询指定列
// // 	FindByAge(ctx context.Context, arg *model.StudentFindByAgeArg) ([]*model.StudentFindByAgeRes, error)

// // 	FindByWithPage(ctx context.Context, arg *model.StudentFindByWithPageArg) (*model.StudentFindByWithPageRes, error)
// // }

// type StudentDao struct {
// 	*db.Repository
// 	TableNameStrategy daoopt.ITableNameStrategy
// }

// // NewStudentDao get dao instance
// func NewStudentDao(repository *db.Repository) dao.IStudentDao {
// 	InitStudentNamingSql()
// 	return &StudentDao{
// 		Repository: repository,
// 	}
// }

// // InsertOne 插入数据
// func (dao *StudentDao) InsertOne(ctx context.Context, arg *model.Student) (int64, error) {
// 	ldb := dao.DB(ctx).Session(&gorm.Session{Context: ctx}) // 每次操作都为单独的session防止污染
// 	// result := dao.DB(ctx).Create(arg)
// 	result := ldb.Create(arg)
// 	return result.RowsAffected, result.Error
// }

// // InsertOneIgnoreZeroVal 插入数据时，自动剔除有omitempty标签且值为零的列
// func (dao *StudentDao) InsertOneIgnoreZeroVal(ctx context.Context, arg *model.Student) (int64, error) {
// 	insertIgnoreZeroValSlice := db.CollectZeroValWithOmitEmpty(arg)
// 	result := dao.DB(ctx).Omit(insertIgnoreZeroValSlice...).Create(arg)
// 	return result.RowsAffected, result.Error
// }

// func (dao *StudentDao) FindByPrimaryKey(ctx context.Context, Id int64) (*model.Student, error) {
// 	findRes := &model.Student{}
// 	result := dao.DB(ctx).Where("ID", Id).Find(findRes)
// 	return findRes, result.Error
// }

// // UpdateByPrimaryKey 根据主键更新，该操作只适合从数据库查询原实体修改值之后使用
// func (dao *StudentDao) UpdateByPrimaryKey(ctx context.Context, arg *model.Student) (int64, error) {
// 	result := dao.DB(ctx).Save(arg)
// 	return result.RowsAffected, result.Error
// }

// // UpdateByPriIngoreNullCols 根据主键更新，自动剔除参数中的零值列
// func (dao *StudentDao) UpdateByPriIngoreNullCols(ctx context.Context, arg *model.Student) (int64, error) {
// 	result := dao.DB(ctx).Model(arg).Updates(arg)
// 	return result.RowsAffected, result.Error
// }

// func (dao *StudentDao) DeleteByPrimaryKey(ctx context.Context, Id int64) (int64, error) {
// 	result := dao.DB(ctx).Where("ID", Id).Delete(&model.Student{})
// 	return result.RowsAffected, result.Error
// }

// func (dao *StudentDao) FindByNameAge(ctx context.Context, Name string, Age int) ([]model.Student, error) {
// 	var list []model.Student
// 	result := dao.DB(ctx).Where("NAME", Name).Where("AGE", Age).Find(&list)
// 	return list, result.Error
// }

// func DbBuilder(ctx context.Context, rootdb *gorm.DB, bfun []func(*gorm.DB) *gorm.DB) *gorm.DB {

// 	// =session前=
// 	// 获取datasource，即获取rootdb
// 	// 事务管理
// 	// session前 的chainable_api 类的构建
// 	// =session=
// 	// session的config
// 	// =session后=
// 	// session后 的chainable_api 类的构建
// 	// finisher_api 的调用

// 	return rootdb
// }

// func (dao *StudentDao) FindByStuno(ctx context.Context, Stuno int64) (*model.Student, error) {
// 	findRes := &model.Student{}

// 	db := dao.DB(ctx)
// 	// mw

// 	aaa := func(ctx context.Context, tableInfo any, db *gorm.DB) daoopt.GormScopeFunc {
// 		return func(db *gorm.DB) *gorm.DB {
// 			return db.Table("xxx")
// 		}
// 	}

// 	var sfunc daoopt.GormScopeFunc
// 	// sfunc = func(db *gorm.DB) *gorm.DB {
// 	// 	return db.Table("xxx")
// 	// }
// 	sfunc = aaa(ctx, nil, db) // 自定义mw

// 	db = db.Scopes(sfunc)
// 	// db = db.Scopes(func(db *gorm.DB) *gorm.DB {
// 	// 	return db.Table("xxx")
// 	// })
// 	// 通过
// 	// db = db.Table("xxxxx") // 修改表名

// 	// opts := make([]DbOpt, 0)

// 	// // 表名mw default name: student
// 	// // db = db.Table("xxx")
// 	// opts = append(opts, func(db *gorm.DB) *gorm.DB {
// 	// 	// 通过策略获取表名
// 	// 	return db.Table("xxx")
// 	// })

// 	db = db.Where("STUNO", Stuno)
// 	db = db.Find(findRes)

// 	result := db
// 	return findRes, result.Error
// }

// // UpdateByStuno 根据唯一索引更新数据,自动剔除零值的列
// func (dao *StudentDao) UpdateByStuno(ctx context.Context, Stuno int64, arg *model.Student) (int64, error) {
// 	// TODO 检查Stuno和实体是否一致

// 	result := dao.DB(ctx).Model(&model.Student{}).Where("STUNO", Stuno).Updates(arg)
// 	return result.RowsAffected, result.Error
// }

// // DeleteByStuno 根据唯一索引作为条件,删除满足条件的数据
// func (dao *StudentDao) DeleteByStuno(ctx context.Context, Stuno int64) (int64, error) {
// 	result := dao.DB(ctx).Where("STUNO", Stuno).Delete(&model.Student{})
// 	return result.RowsAffected, result.Error
// }

// // 查询全部列
// func (dao *StudentDao) FindByAge(ctx context.Context, arg *model.StudentFindByAgeArg) ([]*model.StudentFindByAgeRes, error) {
// 	var list []*model.StudentFindByAgeRes

// 	sqlName := StudentNamingSqlMap[dao.DbType+"_Student_FindByAge"]
// 	if sqlName == "" {
// 		return nil, errors.New("不支持的db类型")
// 	}
// 	newSql, namingparameters := db.ReplaceNamedParamsWithIn(sqlName)
// 	paramters, err := db.GetParamsByNames(arg, namingparameters)
// 	if err != nil {
// 		return nil, err
// 	}
// 	result := dao.DB(ctx).Raw(newSql, paramters...).Find(&list)
// 	return list, result.Error
// }

// // FindByWithPage分页查询
// func (dao *StudentDao) FindByWithPage(ctx context.Context, arg *model.StudentFindByWithPageArg) (*model.StudentFindByWithPageRes, error) {

// 	var list []*model.Student

// 	sqlName := StudentNamingSqlMap[dao.DbType+"_Student_FindByWithPage"]
// 	if sqlName == "" {
// 		return nil, errors.New("不支持的db类型")
// 	}

// 	// 先查询总数
// 	countSql := StudentNamingSqlMap[dao.DbType+"_Student_FindByWithPage_Count"]
// 	if countSql == "" {
// 		return nil, errors.New("不支持的db类型")
// 	}
// 	countNewSql, countNamingparameters := db.ReplaceNamedParamsWithIn(countSql)
// 	countParamters, err := db.GetParamsByNames(arg, countNamingparameters)
// 	if err != nil {
// 		return nil, err
// 	}

// 	var count int64
// 	countResult := dao.DB(ctx).Raw(countNewSql, countParamters...).Scan(&count)
// 	if countResult.Error != nil {
// 		return nil, countResult.Error
// 	}
// 	startRecord, endRecord, totalPage := db.CalcPageStartRecord(arg.PageNum, arg.PageSize, count, dao.DbType)
// 	res := &model.StudentFindByWithPageRes{
// 		PageNum:    arg.PageNum,
// 		PageSize:   arg.PageSize,
// 		TotalPage:  totalPage,
// 		TotalCount: count,
// 		DataRes:    list,
// 	}
// 	if count == 0 {
// 		return res, nil
// 	}
// 	newSql, _ := db.ReplaceNamedParamsWithIn(sqlName)
// 	if startRecord == 0 && endRecord == 0 {
// 		return res, nil
// 	}
// 	countParamters = append(countParamters, startRecord, endRecord)
// 	result := dao.DB(ctx).Raw(newSql, countParamters...).Find(&list)
// 	res.DataRes = list
// 	return res, result.Error
// }
