// Code generated by aic-generate, DO NOT EDIT
// Code generated by aic-generate, DO NOT EDIT
// Code generated by aic-generate, DO NOT EDIT

package daohzw

import (
	"agdemoB/internal/repository/model"
	"context"
	"errors"
	"fmt"
	"reflect"
)

type NamingInfo struct {
	Name  string
	AType interface{}
	BType interface{}
}

type IStudentDao interface {
	InsertOne(ctx context.Context, arg *model.Student) (int64, error)
	InsertOneIgnoreZeroVal(ctx context.Context, arg *model.Student) (int64, error)
	UpdateByPrimaryKey(ctx context.Context, arg *model.Student) (int64, error)
	UpdateByPriIngoreNullCols(ctx context.Context, arg *model.Student) (int64, error)
	DeleteByPrimaryKey(ctx context.Context, Id int64) (int64, error)

	FindByStruct(ctx context.Context, arg *model.Student) ([]model.Student, error)
	// FindByPrimaryKey(ctx context.Context, Id int64) (*model.Student, error)
	// FindByNameAge(ctx context.Context, Name string, Age int) ([]model.Student, error)
	// FindByStuno(ctx context.Context, Stuno int64) (*model.Student, error)
	// UpdateByStuno(ctx context.Context, Stuno int64, arg *model.Student) (int64, error)
	// DeleteByStuno(ctx context.Context, Stuno int64) (int64, error)

	FindByNaming(ctx context.Context, ninfo NamingInfo, arg any) ([]any, error)

	// 查询指定列
	// FindByAge(ctx context.Context, arg *model.StudentFindByAgeArg) ([]*model.StudentFindByAgeRes, error)
	// FindByWithPage(ctx context.Context, arg *model.StudentFindByWithPageArg) (*model.StudentFindByWithPageRes, error)
}

type StudentDao struct {
	DbType string
}

func (dao *StudentDao) FindByNaming(ctx context.Context, ninfo NamingInfo, arg any) ([]any, error) {

	// 根据NamingInfo.AType判断并转换入参(通用逻辑)
	// switch ninfo.AType.(type) {

	// 1. 前置基础校验
	if ctx == nil {
		return nil, errors.New("context is nil")
	}
	if arg == nil {
		return nil, errors.New("arg is nil")
	}
	if ninfo.AType == nil {
		return nil, errors.New("NamingInfo.AType is nil, missing input type info")
	}
	if ninfo.BType == nil {
		return nil, errors.New("NamingInfo.BType is nil, missing output type info")
	}

	// 2. 基于ninfo.AType判断并转换入参（核心通用逻辑）
	targetInType := reflect.TypeOf(ninfo.AType) // 获取目标入参类型
	actualInType := reflect.TypeOf(arg)         // 获取实际入参类型
	if actualInType != targetInType {
		return nil, fmt.Errorf(
			"通用查询：入参类型不匹配，查询[%s]预期[%v]，实际传入[%v]",
			ninfo.Name, targetInType, actualInType,
		)
	}

	// 步骤3：根据ninfo.Name路由到对应的专用查询函数（核心调度逻辑）
	// 专用函数返回强类型结果+error，通用方法仅做转发
	// 通过targetInType 转换入参为目标类型
	// typedArg := reflect.ValueOf(arg).Convert(targetInType).Interface()
	rawResult, err := dao.doxxx(arg) //
	if err != nil {
		return nil, fmt.Errorf("通用查询：查询[%s]执行失败，原因：%w", ninfo.Name, err)
	}

	// 步骤4：强类型结果转换为[]any（公共逻辑，适配方法返回值）
	// 校验结果类型与ninfo.BType匹配，避免专用函数返回错误类型
	targetOutType := reflect.TypeOf(ninfo.BType)
	actualOutType := reflect.TypeOf(rawResult)
	if actualOutType != targetOutType {
		return nil, fmt.Errorf(
			"通用查询：结果类型不匹配，查询[%s]预期[%v]，实际返回[%v]",
			ninfo.Name, targetOutType, actualOutType,
		)
	}
	// 核心优化代码：无遍历实现[]any转换
	rawResultVal := reflect.ValueOf(rawResult)
	// 1. 构造目标类型：[]any
	anyType := reflect.TypeOf((*any)(nil)).Elem() // 获取any的反射类型（interface {}）
	targetSliceType := reflect.SliceOf(anyType)   // 构造[]any的反射类型
	// 2. 强类型切片反射值 整体转换为 []any反射值（零拷贝）
	convertedVal := rawResultVal.Convert(targetSliceType)
	// 3. 转换为Go原生[]any并返回
	result, ok := convertedVal.Interface().([]any)
	if !ok {
		return nil, fmt.Errorf("通用查询：结果转换[]any失败，查询[%s]", ninfo.Name)
	}
	// // 将强类型切片转换为[]any，兼容返回值要求
	// result := make([]any, 0, reflect.ValueOf(rawResult).Len())
	// rawResultVal := reflect.ValueOf(rawResult)
	// for i := 0; i < rawResultVal.Len(); i++ {
	// 	result = append(result, rawResultVal.Index(i).Interface())
	// }

	// 步骤5：无错误，返回封装后的[]any结果
	return result, nil
}

func (dao *StudentDao) FindByNaming2(ctx context.Context, ninfo NamingInfo, arg any) (any, error) {

	// 根据NamingInfo.AType判断并转换入参(通用逻辑)
	// switch ninfo.AType.(type) {

	// 1. 前置基础校验
	if ctx == nil {
		return nil, errors.New("context is nil")
	}
	if arg == nil {
		return nil, errors.New("arg is nil")
	}
	if ninfo.AType == nil {
		return nil, errors.New("NamingInfo.AType is nil, missing input type info")
	}
	if ninfo.BType == nil {
		return nil, errors.New("NamingInfo.BType is nil, missing output type info")
	}

	// 2. 基于ninfo.AType判断并转换入参（核心通用逻辑）
	targetInType := reflect.TypeOf(ninfo.AType) // 获取目标入参类型
	actualInType := reflect.TypeOf(arg)         // 获取实际入参类型
	if actualInType != targetInType {
		return nil, fmt.Errorf(
			"通用查询：入参类型不匹配，查询[%s]预期[%v]，实际传入[%v]",
			ninfo.Name, targetInType, actualInType,
		)
	}

	// 步骤3：根据ninfo.Name路由到对应的专用查询函数（核心调度逻辑）
	// 专用函数返回强类型结果+error，通用方法仅做转发
	// TODO switch name 调用对应的专用查询函数
	rawResult, err := dao.doxxx(arg) // 应该通过NamingInfo中的名字调用实际的查询函数
	if err != nil {
		return nil, fmt.Errorf("通用查询：查询[%s]执行失败，原因：%w", ninfo.Name, err)
	}

	// 步骤4：强类型结果转换为[]any（公共逻辑，适配方法返回值）
	// 校验结果类型与ninfo.BType匹配，避免专用函数返回错误类型
	targetOutType := reflect.TypeOf(ninfo.BType)
	actualOutType := reflect.TypeOf(rawResult)
	if actualOutType != targetOutType {
		return nil, fmt.Errorf(
			"通用查询：结果类型不匹配，查询[%s]预期[%v]，实际返回[%v]",
			ninfo.Name, targetOutType, actualOutType,
		)
	}

	// 步骤5：无错误，返回封装后的[]any结果
	return rawResult, nil
}

var FindByPageNamingInfo = NamingInfo{
	Name:  "FindByWithPage",
	AType: (*PageArg)(nil),
	BType: ([]model.Student)(nil),
}

type PageArg struct{}

func (dao *StudentDao) doxxx(arg any) ([]model.Student, error) {
	rarg, ok := arg.(*PageArg)
	if !ok {
		return nil, fmt.Errorf("FindByWithPage arg type assertion failed")
	}
	fmt.Printf("FindByWithPage arg: %v\n", rarg)
	return nil, nil
}

