// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demob/demoB2.proto

package demobsvc2

import (
	hserver "ag-core/contribute/aghertz/server"
	fx "go.uber.org/fx"
)

var FxDemobsvc2HertzModule = fx.Module("fx_Demobsvc2_hertz",
	FxDemobsvc2_Hello_hertz_RegProvider,
)
var FxDemobsvc2_Hello_hertz_RegProvider = fx.Provide(
	hserver.NewFxServerRouteProvider(
		Router_Demobsvc2_Hello_0_GET_Hertz,
	),
)
