// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demob/demoB2.proto

package demobsvc2

import (
	agclient "ag-core/contribute/aghertz/aghertzclient"
	demob "agdemoB/api/demob"
	"context"
	"github.com/cloudwego/hertz/pkg/app/client"
	config "github.com/cloudwego/hertz/pkg/common/config"
)

// Demobsvc2HertzClient is the hertz client for Demobsvc2.
type Demobsvc2HertzClient interface {
	// Hello
	Hello(ctx context.Context, req *demob.BReq2, opts ...config.RequestOption) (resp *demob.BRep2, err error)
}

// NewDemobsvc2HertzClient is the constructor for Demobsvc2HertzClient.
func NewDemobsvc2HertzClient(hc *client.Client, opts ...agclient.AgHertzClientOption) Demobsvc2HertzClient {
	client := &Demobsvc2HertzClientImpl{
		HertzBaseClient: agclient.NewHertzBaseClient(hc, opts...),
	}
	return client
}

// Demobsvc2HertzClientImpl is the hertz client impl for Demobsvc2.
type Demobsvc2HertzClientImpl struct {
	*agclient.HertzBaseClient
}

// Hello client impl Hello
func (c *Demobsvc2HertzClientImpl) Hello(ctx context.Context, req *demob.BReq2, opts ...config.RequestOption) (*demob.BRep2, error) {
	var resp demob.BRep2

	// 构建请求配置
	reqParam := &agclient.RequestParam{
		Method: "GET",
		Path:   "v2/hello",
	}
	rerr := c.DoRequest(ctx, reqParam, nil, &resp, opts...)
	if rerr != nil {
		return nil, rerr
	}

	return &resp, nil
}
