// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demob/demoB2.proto

package demobsvc2

import (
	hserver "ag-core/contribute/aghertz/server"
	demob "agdemoB/api/demob"
	"context"
	app "github.com/cloudwego/hertz/pkg/app"
	consts "github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Router_Demobsvc2_Hello_0_GET_Hertz
// @Name: Hello
// @Method: GET
// @Path: v2/hello
func Router_Demobsvc2_Hello_0_GET_Hertz(s demob.Demobsvc2) *hserver.Route {
	return &hserver.Route{
		HttpMethod:   "GET",
		RelativePath: "v2/hello",
		Handlers:     append(make([]app.HandlerFunc, 0), _Demobsvc2_Hello_0_HTTP_Handler(s)),
	}
}

func _Demobsvc2_Hello_0_HTTP_Handler(s demob.Demobsvc2) func(ctx context.Context, c *app.RequestContext) {
	return func(ctx context.Context, c *app.RequestContext) {
		//var in = new(demob.BReq2)
		var in demob.BReq2
		// 无Body定义的方法，BindQuery，否则使用BindByContentType
		if err := c.BindQuery(&in); err != nil {
			c.String(consts.StatusBadRequest, err.Error())
			return
		}

		resp, err := s.Hello(ctx, &in)
		if err != nil {
			// TODO 增强异常处理
			c.String(consts.StatusInternalServerError, err.Error())
			return
		}

		// c.JSON 会自动将 Content-Type 设置为 application/json,
		c.JSON(consts.StatusOK, resp)
	}
}
