// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
//
// GenScope: package_group
// Versions:
//   - agserver: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demob/demoB.proto
//   - demob/demoB2.proto

package demob

import (
	"context"
)

// Demob defines the server interface for the Demob service.
type Demob interface {
	Calldemob(context.Context, *BRequest) (*BReply, error)
}

// Demobsvc2 defines the server interface for the Demobsvc2 service.
type Demobsvc2 interface {
	Hello(context.Context, *BReq2) (*BRep2, error)
}
