// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: demob/demoB2.proto

package demob

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BReq2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BReq2) Reset() {
	*x = BReq2{}
	mi := &file_demob_demoB2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BReq2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BReq2) ProtoMessage() {}

func (x *BReq2) ProtoReflect() protoreflect.Message {
	mi := &file_demob_demoB2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BReq2.ProtoReflect.Descriptor instead.
func (*BReq2) Descriptor() ([]byte, []int) {
	return file_demob_demoB2_proto_rawDescGZIP(), []int{0}
}

func (x *BReq2) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BRep2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BRep2) Reset() {
	*x = BRep2{}
	mi := &file_demob_demoB2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BRep2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BRep2) ProtoMessage() {}

func (x *BRep2) ProtoReflect() protoreflect.Message {
	mi := &file_demob_demoB2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BRep2.ProtoReflect.Descriptor instead.
func (*BRep2) Descriptor() ([]byte, []int) {
	return file_demob_demoB2_proto_rawDescGZIP(), []int{1}
}

func (x *BRep2) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_demob_demoB2_proto protoreflect.FileDescriptor

const file_demob_demoB2_proto_rawDesc = "" +
	"\n" +
	"\x12demob/demoB2.proto\x12\tapi.demob\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/descriptor.proto\"\x1b\n" +
	"\x05BReq2\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x19\n" +
	"\x05BRep2\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2M\n" +
	"\tdemobsvc2\x12@\n" +
	"\x05hello\x12\x10.api.demob.BReq2\x1a\x10.api.demob.BRep2\"\x13\x82\xd3\xe4\x93\x02\rb\x01*\x12\bv2/helloB\x13Z\x11agdemoB/api/demobb\x06proto3"

var (
	file_demob_demoB2_proto_rawDescOnce sync.Once
	file_demob_demoB2_proto_rawDescData []byte
)

func file_demob_demoB2_proto_rawDescGZIP() []byte {
	file_demob_demoB2_proto_rawDescOnce.Do(func() {
		file_demob_demoB2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_demob_demoB2_proto_rawDesc), len(file_demob_demoB2_proto_rawDesc)))
	})
	return file_demob_demoB2_proto_rawDescData
}

var file_demob_demoB2_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_demob_demoB2_proto_goTypes = []any{
	(*BReq2)(nil), // 0: api.demob.BReq2
	(*BRep2)(nil), // 1: api.demob.BRep2
}
var file_demob_demoB2_proto_depIdxs = []int32{
	0, // 0: api.demob.demobsvc2.hello:input_type -> api.demob.BReq2
	1, // 1: api.demob.demobsvc2.hello:output_type -> api.demob.BRep2
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_demob_demoB2_proto_init() }
func file_demob_demoB2_proto_init() {
	if File_demob_demoB2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_demob_demoB2_proto_rawDesc), len(file_demob_demoB2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demob_demoB2_proto_goTypes,
		DependencyIndexes: file_demob_demoB2_proto_depIdxs,
		MessageInfos:      file_demob_demoB2_proto_msgTypes,
	}.Build()
	File_demob_demoB2_proto = out.File
	file_demob_demoB2_proto_goTypes = nil
	file_demob_demoB2_proto_depIdxs = nil
}
