// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: demob/demoB.proto

package demob

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BRequest) Reset() {
	*x = BRequest{}
	mi := &file_demob_demoB_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BRequest) ProtoMessage() {}

func (x *BRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demob_demoB_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BRequest.ProtoReflect.Descriptor instead.
func (*BRequest) Descriptor() ([]byte, []int) {
	return file_demob_demoB_proto_rawDescGZIP(), []int{0}
}

func (x *BRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BReply) Reset() {
	*x = BReply{}
	mi := &file_demob_demoB_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BReply) ProtoMessage() {}

func (x *BReply) ProtoReflect() protoreflect.Message {
	mi := &file_demob_demoB_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BReply.ProtoReflect.Descriptor instead.
func (*BReply) Descriptor() ([]byte, []int) {
	return file_demob_demoB_proto_rawDescGZIP(), []int{1}
}

func (x *BReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_demob_demoB_proto protoreflect.FileDescriptor

const file_demob_demoB_proto_rawDesc = "" +
	"\n" +
	"\x11demob/demoB.proto\x12\tapi.demob\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/descriptor.proto\"\x1e\n" +
	"\bBRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1a\n" +
	"\x06BReply\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2U\n" +
	"\x05demob\x12L\n" +
	"\tcalldemob\x12\x13.api.demob.BRequest\x1a\x11.api.demob.BReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*b\x01*\"\tcalldemoBB\x13Z\x11agdemoB/api/demobb\x06proto3"

var (
	file_demob_demoB_proto_rawDescOnce sync.Once
	file_demob_demoB_proto_rawDescData []byte
)

func file_demob_demoB_proto_rawDescGZIP() []byte {
	file_demob_demoB_proto_rawDescOnce.Do(func() {
		file_demob_demoB_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_demob_demoB_proto_rawDesc), len(file_demob_demoB_proto_rawDesc)))
	})
	return file_demob_demoB_proto_rawDescData
}

var file_demob_demoB_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_demob_demoB_proto_goTypes = []any{
	(*BRequest)(nil), // 0: api.demob.BRequest
	(*BReply)(nil),   // 1: api.demob.BReply
}
var file_demob_demoB_proto_depIdxs = []int32{
	0, // 0: api.demob.demob.calldemob:input_type -> api.demob.BRequest
	1, // 1: api.demob.demob.calldemob:output_type -> api.demob.BReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_demob_demoB_proto_init() }
func file_demob_demoB_proto_init() {
	if File_demob_demoB_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_demob_demoB_proto_rawDesc), len(file_demob_demoB_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demob_demoB_proto_goTypes,
		DependencyIndexes: file_demob_demoB_proto_depIdxs,
		MessageInfos:      file_demob_demoB_proto_msgTypes,
	}.Build()
	File_demob_demoB_proto = out.File
	file_demob_demoB_proto_goTypes = nil
	file_demob_demoB_proto_depIdxs = nil
}
