package model
import (
	"fmt"
	db "ag-core/contribute/agdb/gormdb"
	"ag-core/contribute/agdb/conditonwhere"
	"gopkg.in/yaml.v2"
	"time"
)
// Student 表模型
// AUTOGENERATED: DO NOT EDIT
type Student struct {
	Id int64 `gorm:"column:ID;primaryKey;not null" json:"Id"`
	Stuno int64 `gorm:"column:STUNO;index:STUNO_UNIUQE_1,priority:1" json:"Stuno"`
	Name string `gorm:"column:NAME;index:INDEX_NAME_AGE,priority:1" json:"Name"`
	Age int `gorm:"column:AGE;index:INDEX_NAME_AGE,priority:2;index:INDEX_AGE,priority:1" json:"Age"`
	Version int64 `gorm:"column:VERSION" json:"Version"`
	Fct time.Time `gorm:"column:FCT" json:"Fct"`
	Lct time.Time `gorm:"column:LCT" json:"Lct"`
}

// StudentPrimaryKey 单主键类型别名
type StudentPrimaryKey int64

// TableName 返回表名
func (student *Student) TableName() string {
	return "STUDENT"
}

// Clone 克隆对象
func (student *Student) Clone() *Student {
	if student == nil {
		return nil
	}
	return &Student{
		Id: student.Id,
		Stuno: student.Stuno,
		Name: student.Name,
		Age: student.Age,
		Version: student.Version,
		Fct: student.Fct,
		Lct: student.Lct,
	}
}

// ListZeroValueCols 列出零值列或非零值列
// filterPrimary: false-主键列正常处理 true-主键列被过滤掉
// filterIndex: false-索引列正常处理 true-索引列被过滤掉
// filterIsZero: false-只获取零值的列, true-只获取非零值的列
// filterSpecial: 是否过滤特殊列(jpaVersion/createTime/lastUpdateTime)
func (student *Student) ListZeroValueCols(filterPrimary bool, filterIndex bool, filterIsZero bool, filterSpecial bool) ([]string, []interface{}, error) {
	if student == nil {
		return nil, nil, fmt.Errorf("student is nil")
	}

	var cols []string
	var vals []interface{}

 // generalColZeroVal 用于普通列的零值检查，避免重复代码
	var generalColZeroVal bool = false
	

	// Id - 主键，索引列
	if !filterPrimary {
		isZero := student.Id == 0
		// false 保留零值 true 过滤零值
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "ID")
			vals = append(vals, student.Id)
		}
	}

	// Stuno - 索引列
	if !filterIndex {
		isZero := student.Stuno == 0
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "STUNO")
			vals = append(vals, student.Stuno)
		}
	}

	// Name - 索引列
	if !filterIndex {
		isZero := student.Name == ""
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "NAME")
			vals = append(vals, student.Name)
		}
	}

	// Age - 索引列
	if !filterIndex {
		isZero := student.Age == 0
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "AGE")
			vals = append(vals, student.Age)
		}
	}

	// Version - 普通列
	generalColZeroVal = student.Version == 0
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "VERSION")
		vals = append(vals, student.Version)
	}

	// Fct - 普通列
	generalColZeroVal = student.Fct.IsZero()
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "FCT")
		vals = append(vals, student.Fct)
	}

	// Lct - 普通列
	generalColZeroVal = student.Lct.IsZero()
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "LCT")
		vals = append(vals, student.Lct)
	}

	return cols, vals, nil
}

// ToString 转换为字符串
func (student *Student) ToString() string {
	if student == nil {
		return ""
	}
	return fmt.Sprintf("Student:(%+v)", *student)
}

// StudentAllowUpdateCols 支持更新的列名列表
var StudentAllowUpdateCols = []string{}

// StudentIndexLeadingCols 索引前导列，用于检查是否走了索引，避免全表扫描
// 列名必须和数据库表列名一致，区分大小写
var StudentIndexLeadingCols = []string{"ID", "NAME", "AGE", "STUNO"}



// StudentFindByAgeArg FindByAge 查询参数
type StudentFindByAgeArg struct {
	FieldMask *conditonwhere.FieldMask
	Age int
	Stuno int64
}

func (studentFindByAgeArg *StudentFindByAgeArg) WithAge(Age int) *StudentFindByAgeArg{
	studentFindByAgeArg.Age = Age
	studentFindByAgeArg.FieldMask.Set("Age")
	return studentFindByAgeArg
} 

func (studentFindByAgeArg *StudentFindByAgeArg) WithStuno(Stuno int64) *StudentFindByAgeArg{
	studentFindByAgeArg.Stuno = Stuno
	studentFindByAgeArg.FieldMask.Set("Stuno")
	return studentFindByAgeArg
} 

// ConvertToMap 将参数转换为map
func (studentFindByAgeArg *StudentFindByAgeArg) ConvertToMap() map[string]interface{} {
	if studentFindByAgeArg == nil {
		return nil
	}
	return map[string]interface{}{
		"Age": studentFindByAgeArg.Age,
		"Stuno": studentFindByAgeArg.Stuno,
	}
}

// StudentFindByAgeRes FindByAge 查询结果
type StudentFindByAgeRes struct {
	Id int64 `gorm:"column:ID" json:"Id"`
	Stuno int64 `gorm:"column:STUNO" json:"Stuno"`
	Name string `gorm:"column:NAME" json:"Name"`
	Age int `gorm:"column:AGE" json:"Age"`
}

// StudentFindByWithPageArg FindByWithPage 查询参数
type StudentFindByWithPageArg struct {
	db.Page
	FieldMask *conditonwhere.FieldMask
	Age int
}

func (studentFindByWithPageArg *StudentFindByWithPageArg) WithAge(Age int) *StudentFindByWithPageArg{
	studentFindByWithPageArg.Age = Age
	studentFindByWithPageArg.FieldMask.Set("Age")
	return studentFindByWithPageArg
} 

// ConvertToMap 将参数转换为map
func (studentFindByWithPageArg *StudentFindByWithPageArg) ConvertToMap() map[string]interface{} {
	if studentFindByWithPageArg == nil {
		return nil
	}
	return map[string]interface{}{
		"Page": studentFindByWithPageArg.Page,
		"Age": studentFindByWithPageArg.Age,
	}
}

// StudentFindByWithPagePageRes FindByWithPage 分页查询结果
type StudentFindByWithPagePageRes struct {
	db.PageResult
	ResultList []*Student
}



// WhereDataToYAMLCache WhereDataYAML缓存
var StudentWhereDataToYAMLCache = map[string]string{
	"FindByAge":`conditions:
- expr: AGE = @Age
- expr: STUNO > @Stuno
operator: AND
`,
	"FindByWithPage":`conditions:
- expr: AGE = @Age
operator: AND
`,
}


var StudentConditionMap = map[string]*conditonwhere.MaskWhereCondition{}

// 初始注册自定义函数的condition
func init() {
	for key, whereDataYaml := range StudentWhereDataToYAMLCache {
		var newData map[interface{}]interface{}
		yaml.Unmarshal([]byte(whereDataYaml), &newData)
		 StudentConditionMap[key] = conditonwhere.ParseWhereCondition(newData)
	}
}
