// Code generated by aic-generate, DO NOT EDIT
// Code generated by aic-generate, DO NOT EDIT
// Code generated by aic-generate, DO NOT EDIT

package model
import (
	"fmt"
	"time"
)

// Student mapped from table student
type Student struct {
   Id  int64 `gorm:"column:ID;primaryKey;not null" json:"Id"`
   Stuno  int64 `gorm:"column:STUNO;not null;index:STUNO_UNIUQE_1,priority:1" json:"Stuno"`
   Name  string `gorm:"column:NAME;index:INDEX_NAME_AGE,priority:1" json:"Name"`
   Age  int `gorm:"column:AGE;not null;index:INDEX_NAME_AGE,priority:2" json:"Age"`
   Version  int64 `gorm:"column:VERSION" json:"Version"`
   Fct  time.Time `gorm:"AUTOCREATETIME;column:FCT" json:"Fct"`
   Lct  time.Time `gorm:"AUTOUPDATETIME;column:LCT" json:"Lct"`
}
type StudentFindByAgeArg struct {
   Age  int
   
   Stuno  int64
   
}


type StudentFindByWithPageArg struct {
   Age  int
   
}



// 指定列查询返回实体定义

type StudentFindByAgeRes struct {
   Id  int64 `gorm:"column:ID"`
   Stuno  int64 `gorm:"column:STUNO"`
   Name  string `gorm:"column:NAME"`
   Age  int `gorm:"column:AGE"`
}


// TableName student table name
func (*Student) TableName() string {
   return "student"
}


func (owner *Student) Clone() *Student {
   if owner == nil{
      return nil
   }
   return &Student{
      Id        : owner.Id,
      Stuno     : owner.Stuno,
      Name      : owner.Name,
      Age       : owner.Age,
      Version   : owner.Version,
      Fct       : owner.Fct,
      Lct       : owner.Lct,
   }
}

func (owner *Student) ToString() string {
    if owner == nil{
      return "<nil>"
    }
    return fmt.Sprintf("Student:(%+v)", *owner)
}