// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressb/stressb.proto

package bservice

import (
	agclient "ag-core/contribute/aghertz/aghertzclient"
	stressb "ag_stress_b/api/stressb"
	"context"
	"github.com/cloudwego/hertz/pkg/app/client"
	config "github.com/cloudwego/hertz/pkg/common/config"
)

// BServiceHertzClient is the hertz client for BService.
type BServiceHertzClient interface {
	// EchoB
	EchoB(ctx context.Context, req *stressb.EchoBRequest, opts ...config.RequestOption) (resp *stressb.EchoBResponse, err error)
}

// NewBServiceHertzClient is the constructor for BServiceHertzClient.
func NewBServiceHertzClient(hc *client.Client, opts ...agclient.AgHertzClientOption) BServiceHertzClient {
	client := &BServiceHertzClientImpl{
		HertzBaseClient: agclient.NewHertzBaseClient(hc, opts...),
	}
	return client
}

// BServiceHertzClientImpl is the hertz client impl for BService.
type BServiceHertzClientImpl struct {
	*agclient.HertzBaseClient
}

// EchoB client impl EchoB
func (c *BServiceHertzClientImpl) EchoB(ctx context.Context, req *stressb.EchoBRequest, opts ...config.RequestOption) (*stressb.EchoBResponse, error) {
	var resp stressb.EchoBResponse

	// 构建请求配置
	reqParam := &agclient.RequestParam{
		Method: "POST",
		Path:   "echo/b",
	}
	rerr := c.DoRequest(ctx, reqParam, req, &resp, opts...)
	if rerr != nil {
		return nil, rerr
	}

	return &resp, nil
}
