// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressc/stressc.proto

package cservice

import (
	akserver "ag-core/contribute/agkitex/server"
	fx "go.uber.org/fx"
)

// FxCServiceKitexModule fx module
var FxCServiceKitexModule = fx.Module("fx_CService_kitex",
	FxCServiceKitexRegProvider,
)

// FxCServiceKitexRegProvider fx provide
var FxCServiceKitexRegProvider = fx.Provide(

	akserver.NewFxAgKitexServiceRegistry(
		Register_CService_KitexServer,
	),
)
