// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demoa/demoA.proto

package demoa

import (
	hserver "ag-core/contribute/aghertz/server"
	demoa "agdemoA/api/demoa"
	"context"
	app "github.com/cloudwego/hertz/pkg/app"
	consts "github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Router_DemoA_Calldemoa_0_POST_Hertz
// @Name: Calldemoa
// @Method: POST
// @Path: calldemoA
func Router_DemoA_Calldemoa_0_POST_Hertz(s demoa.DemoA) *hserver.Route {
	return &hserver.Route{
		HttpMethod:   "POST",
		RelativePath: "calldemoA",
		Handlers:     append(make([]app.HandlerFunc, 0), _DemoA_Calldemoa_0_HTTP_Handler(s)),
	}
}

func _DemoA_Calldemoa_0_HTTP_Handler(s demoa.DemoA) func(ctx context.Context, c *app.RequestContext) {
	return func(ctx context.Context, c *app.RequestContext) {
		//var in = new(demoa.ARequest)
		var in demoa.ARequest
		// BindByContentType 当Method为GET时，会自动调用BindQuery，其他方法会调用对应Bind
		if err := c.BindByContentType(&in); err != nil {
			c.String(consts.StatusBadRequest, err.Error())
			return
		}

		resp, err := s.Calldemoa(ctx, &in)
		if err != nil {
			// TODO 增强异常处理
			c.String(consts.StatusInternalServerError, err.Error())
			return
		}

		// c.JSON 会自动将 Content-Type 设置为 application/json,
		c.JSON(consts.StatusOK, resp)
	}
}
