// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demoa/demoA.proto

package demoa

import (
	hserver "ag-core/contribute/aghertz/server"
	fx "go.uber.org/fx"
)

var FxDemoAHertzModule = fx.Module("fx_DemoA_hertz",
	FxDemoA_Calldemoa_hertz_RegProvider,
)
var FxDemoA_Calldemoa_hertz_RegProvider = fx.Provide(
	hserver.NewFxServerRouteProvider(
		Router_DemoA_Calldemoa_0_POST_Hertz,
	),
)
