// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demob/demoB2.proto

package demobsvc2

import (
	demob "agdemoB/api/demob"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var demobsvc2ServiceMethods = map[string]kitex.MethodInfo{
	"hello": kitex.NewMethodInfo(
		helloHandler,
		newHelloArgs,
		newHelloResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	demobsvc2ServiceInfo                = NewServiceInfo()
	demobsvc2ServiceInfoForClient       = NewServiceInfoForClient()
	demobsvc2ServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return demobsvc2ServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return demobsvc2ServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return demobsvc2ServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "demobsvc2"
	handlerType := (*demob.Demobsvc2)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range demobsvc2ServiceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "api.demob",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.14.1_by_aggen", // FIXME 模板生成时应该获取kitex版本
		Extra:           extra,
	}
	return svcInfo
}

func helloHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(demob.BReq2)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(demob.Demobsvc2).Hello(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *HelloArgs:
		success, err := handler.(demob.Demobsvc2).Hello(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*HelloResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newHelloArgs() interface{} {
	return &HelloArgs{}
}

func newHelloResult() interface{} {
	return &HelloResult{}
}

type HelloArgs struct {
	Req *demob.BReq2
}

func (p *HelloArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *HelloArgs) Unmarshal(in []byte) error {
	msg := new(demob.BReq2)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var HelloArgs_Req_DEFAULT *demob.BReq2

func (p *HelloArgs) GetReq() *demob.BReq2 {
	if !p.IsSetReq() {
		return HelloArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *HelloArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *HelloArgs) GetFirstArgument() interface{} {
	return p.Req
}

type HelloResult struct {
	Success *demob.BRep2
}

var HelloResult_Success_DEFAULT *demob.BRep2

func (p *HelloResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *HelloResult) Unmarshal(in []byte) error {
	msg := new(demob.BRep2)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *HelloResult) GetSuccess() *demob.BRep2 {
	if !p.IsSetSuccess() {
		return HelloResult_Success_DEFAULT
	}
	return p.Success
}

func (p *HelloResult) SetSuccess(x interface{}) {
	p.Success = x.(*demob.BRep2)
}

func (p *HelloResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *HelloResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Hello(ctx context.Context, Req *demob.BReq2) (r *demob.BRep2, err error) {
	var _args HelloArgs
	_args.Req = Req
	var _result HelloResult
	if err = p.c.Call(ctx, "hello", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
