// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demob/demoB2.proto

package demobsvc2

import (
	akserver "ag-core/contribute/agkitex/server"
	fx "go.uber.org/fx"
)

// FxDemobsvc2KitexModule fx module
var FxDemobsvc2KitexModule = fx.Module("fx_Demobsvc2_kitex",
	FxDemobsvc2KitexRegProvider,
)

// FxDemobsvc2KitexRegProvider fx provide
var FxDemobsvc2KitexRegProvider = fx.Provide(

	akserver.NewFxAgKitexServiceRegistry(
		Register_Demobsvc2_KitexServer,
	),
)
