// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - hello/hello.proto

package hello

import (
	hserver "ag-core/contribute/aghertz/server"
	fx "go.uber.org/fx"
)

var FxHelloHertzModule = fx.Module("fx_Hello_hertz",
	FxHello_Pinghello_hertz_RegProvider,
)
var FxHello_Pinghello_hertz_RegProvider = fx.Provide(
	hserver.NewFxServerRouteProvider(
		Router_Hello_Pinghello_0_POST_Hertz,
	),
)
