// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - hello/hello.proto

package hello

import (
	hserver "ag-core/contribute/aghertz/server"
	hello "agdemoC/api/hello"
	"context"
	app "github.com/cloudwego/hertz/pkg/app"
	consts "github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Router_Hello_Pinghello_0_POST_Hertz
// @Name: Pinghello
// @Method: POST
// @Path: pinghello
func Router_Hello_Pinghello_0_POST_Hertz(s hello.Hello) *hserver.Route {
	return &hserver.Route{
		HttpMethod:   "POST",
		RelativePath: "pinghello",
		Handlers:     append(make([]app.HandlerFunc, 0), _Hello_Pinghello_0_HTTP_Handler(s)),
	}
}

func _Hello_Pinghello_0_HTTP_Handler(s hello.Hello) func(ctx context.Context, c *app.RequestContext) {
	return func(ctx context.Context, c *app.RequestContext) {
		//var in = new(hello.HelloRequest)
		var in hello.HelloRequest
		// BindByContentType 当Method为GET时，会自动调用BindQuery，其他方法会调用对应Bind
		if err := c.BindByContentType(&in); err != nil {
			c.String(consts.StatusBadRequest, err.Error())
			return
		}

		resp, err := s.Pinghello(ctx, &in)
		if err != nil {
			// TODO 增强异常处理
			c.String(consts.StatusInternalServerError, err.Error())
			return
		}

		// c.JSON 会自动将 Content-Type 设置为 application/json,
		c.JSON(consts.StatusOK, resp)
	}
}
