// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
//
// GenScope: package_group
// Versions:
//   - agserver: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - hzw/hellostreaming.proto
//   - hzw/hzw.proto
//   - hzw/hzw2.proto

package hzw

import (
	"context"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
)

// HelloStream defines the server interface for the HelloStream service.
type HelloStream interface {
	NoStreaming(context.Context, *Request) (*Response, error)
	ClientSideStreaming(stream HelloStream_ClientSideStreamingServer) (err error)
	ServerSideStreaming(req *Request, stream HelloStream_ServerSideStreamingServer) (err error)
	BidiSideStreaming(stream HelloStream_BidiSideStreamingServer) (err error)
}

// HelloStream_ClientSideStreamingServer
type HelloStream_ClientSideStreamingServer interface {
	streaming.Stream
	Recv() (*Request, error)
	SendAndClose(*Response) error
}

// HelloStream_ServerSideStreamingServer
type HelloStream_ServerSideStreamingServer interface {
	streaming.Stream
	Send(*Response) error
}

// HelloStream_BidiSideStreamingServer
type HelloStream_BidiSideStreamingServer interface {
	streaming.Stream
	Recv() (*Request, error)
	Send(*Response) error
}

// HzwHello defines the server interface for the HzwHello service.
type HzwHello interface {
	HelloHzw(context.Context, *HzwRequest) (*HzwReply, error)
	HelloHzwStream(stream HzwHello_HelloHzwStreamServer) (err error)
}

// HzwHello_HelloHzwStreamServer
type HzwHello_HelloHzwStreamServer interface {
	streaming.Stream
	Recv() (*HzwRequest, error)
	Send(*HzwReply) error
}

// HzwHello2 defines the server interface for the HzwHello2 service.
type HzwHello2 interface {
	HelloHzw2(context.Context, *HzwRequest2) (*HzwReply2, error)
	HelloHzwStream2(stream HzwHello2_HelloHzwStream2Server) (err error)
}

// HzwHello2_HelloHzwStream2Server
type HzwHello2_HelloHzwStream2Server interface {
	streaming.Stream
	Recv() (*HzwRequest2, error)
	Send(*HzwReply2) error
}
