// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// hzw/hellostreaming.proto is a deprecated file.

package hzw

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Deprecated: The entire proto file hzw/hellostreaming.proto is marked as deprecated.
type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: The entire proto file hzw/hellostreaming.proto is marked as deprecated.
	Msg           string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_hzw_hellostreaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_hzw_hellostreaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_hzw_hellostreaming_proto_rawDescGZIP(), []int{0}
}

// Deprecated: The entire proto file hzw/hellostreaming.proto is marked as deprecated.
func (x *Request) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// Deprecated: The entire proto file hzw/hellostreaming.proto is marked as deprecated.
type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: The entire proto file hzw/hellostreaming.proto is marked as deprecated.
	Msg           string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_hzw_hellostreaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_hzw_hellostreaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_hzw_hellostreaming_proto_rawDescGZIP(), []int{1}
}

// Deprecated: The entire proto file hzw/hellostreaming.proto is marked as deprecated.
func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_hzw_hellostreaming_proto protoreflect.FileDescriptor

const file_hzw_hellostreaming_proto_rawDesc = "" +
	"\n" +
	"\x18hzw/hellostreaming.proto\x12\aapi.hzw\"\x1b\n" +
	"\aRequest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\x1c\n" +
	"\bResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2\x83\x02\n" +
	"\vHelloStream\x124\n" +
	"\vNoStreaming\x12\x10.api.hzw.Request\x1a\x11.api.hzw.Response\"\x00\x12>\n" +
	"\x13ClientSideStreaming\x12\x10.api.hzw.Request\x1a\x11.api.hzw.Response\"\x00(\x01\x12>\n" +
	"\x13ServerSideStreaming\x12\x10.api.hzw.Request\x1a\x11.api.hzw.Response\"\x000\x01\x12>\n" +
	"\x11BidiSideStreaming\x12\x10.api.hzw.Request\x1a\x11.api.hzw.Response\"\x00(\x010\x01B;\n" +
	"\aapi.hzwB\x10HelloStreamProtoP\x01Z\x19github.hzw.cn/api/hzw;hzw\xb8\x01\x01b\x06proto3"

var (
	file_hzw_hellostreaming_proto_rawDescOnce sync.Once
	file_hzw_hellostreaming_proto_rawDescData []byte
)

func file_hzw_hellostreaming_proto_rawDescGZIP() []byte {
	file_hzw_hellostreaming_proto_rawDescOnce.Do(func() {
		file_hzw_hellostreaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hzw_hellostreaming_proto_rawDesc), len(file_hzw_hellostreaming_proto_rawDesc)))
	})
	return file_hzw_hellostreaming_proto_rawDescData
}

var file_hzw_hellostreaming_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hzw_hellostreaming_proto_goTypes = []any{
	(*Request)(nil),  // 0: api.hzw.Request
	(*Response)(nil), // 1: api.hzw.Response
}
var file_hzw_hellostreaming_proto_depIdxs = []int32{
	0, // 0: api.hzw.HelloStream.NoStreaming:input_type -> api.hzw.Request
	0, // 1: api.hzw.HelloStream.ClientSideStreaming:input_type -> api.hzw.Request
	0, // 2: api.hzw.HelloStream.ServerSideStreaming:input_type -> api.hzw.Request
	0, // 3: api.hzw.HelloStream.BidiSideStreaming:input_type -> api.hzw.Request
	1, // 4: api.hzw.HelloStream.NoStreaming:output_type -> api.hzw.Response
	1, // 5: api.hzw.HelloStream.ClientSideStreaming:output_type -> api.hzw.Response
	1, // 6: api.hzw.HelloStream.ServerSideStreaming:output_type -> api.hzw.Response
	1, // 7: api.hzw.HelloStream.BidiSideStreaming:output_type -> api.hzw.Response
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hzw_hellostreaming_proto_init() }
func file_hzw_hellostreaming_proto_init() {
	if File_hzw_hellostreaming_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hzw_hellostreaming_proto_rawDesc), len(file_hzw_hellostreaming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hzw_hellostreaming_proto_goTypes,
		DependencyIndexes: file_hzw_hellostreaming_proto_depIdxs,
		MessageInfos:      file_hzw_hellostreaming_proto_msgTypes,
	}.Build()
	File_hzw_hellostreaming_proto = out.File
	file_hzw_hellostreaming_proto_goTypes = nil
	file_hzw_hellostreaming_proto_depIdxs = nil
}
