// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: hzw/hzw.proto

package hzw

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HzwRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HzwRequest) Reset() {
	*x = HzwRequest{}
	mi := &file_hzw_hzw_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HzwRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HzwRequest) ProtoMessage() {}

func (x *HzwRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hzw_hzw_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HzwRequest.ProtoReflect.Descriptor instead.
func (*HzwRequest) Descriptor() ([]byte, []int) {
	return file_hzw_hzw_proto_rawDescGZIP(), []int{0}
}

func (x *HzwRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HzwReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HzwReply) Reset() {
	*x = HzwReply{}
	mi := &file_hzw_hzw_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HzwReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HzwReply) ProtoMessage() {}

func (x *HzwReply) ProtoReflect() protoreflect.Message {
	mi := &file_hzw_hzw_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HzwReply.ProtoReflect.Descriptor instead.
func (*HzwReply) Descriptor() ([]byte, []int) {
	return file_hzw_hzw_proto_rawDescGZIP(), []int{1}
}

func (x *HzwReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_hzw_hzw_proto protoreflect.FileDescriptor

const file_hzw_hzw_proto_rawDesc = "" +
	"\n" +
	"\rhzw/hzw.proto\x12\aapi.hzw\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a google/protobuf/descriptor.proto\"&\n" +
	"\n" +
	"HzwRequest\x12\x18\n" +
	"\x04name\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x04name\"\x1c\n" +
	"\bHzwReply\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2\xfd\x01\n" +
	"\bHzwHello\x12\x9d\x01\n" +
	"\bHelloHzw\x12\x13.api.hzw.HzwRequest\x1a\x11.api.hzw.HzwReply\"i\x82\xd3\xe4\x93\x02cZ\x15b\x03msg\x12\x0e/v1/hello/get2Z\x1bb\x03msg\x12\x14/v1/hzw/hello2/:NameZ\x13:\x01*\"\x0e/v1/hzw/hello3b\x03msg\x12\x13/v1/hzw/hello/:Name\x12Q\n" +
	"\x0eHelloHzwStream\x12\x13.api.hzw.HzwRequest\x1a\x11.api.hzw.HzwReply\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/xxxx(\x010\x01B0\n" +
	"\aapi.hzwB\bHzwProtoP\x01Z\x19github.hzw.cn/api/hzw;hzwb\x06proto3"

var (
	file_hzw_hzw_proto_rawDescOnce sync.Once
	file_hzw_hzw_proto_rawDescData []byte
)

func file_hzw_hzw_proto_rawDescGZIP() []byte {
	file_hzw_hzw_proto_rawDescOnce.Do(func() {
		file_hzw_hzw_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hzw_hzw_proto_rawDesc), len(file_hzw_hzw_proto_rawDesc)))
	})
	return file_hzw_hzw_proto_rawDescData
}

var file_hzw_hzw_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hzw_hzw_proto_goTypes = []any{
	(*HzwRequest)(nil), // 0: api.hzw.HzwRequest
	(*HzwReply)(nil),   // 1: api.hzw.HzwReply
}
var file_hzw_hzw_proto_depIdxs = []int32{
	0, // 0: api.hzw.HzwHello.HelloHzw:input_type -> api.hzw.HzwRequest
	0, // 1: api.hzw.HzwHello.HelloHzwStream:input_type -> api.hzw.HzwRequest
	1, // 2: api.hzw.HzwHello.HelloHzw:output_type -> api.hzw.HzwReply
	1, // 3: api.hzw.HzwHello.HelloHzwStream:output_type -> api.hzw.HzwReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hzw_hzw_proto_init() }
func file_hzw_hzw_proto_init() {
	if File_hzw_hzw_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hzw_hzw_proto_rawDesc), len(file_hzw_hzw_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hzw_hzw_proto_goTypes,
		DependencyIndexes: file_hzw_hzw_proto_depIdxs,
		MessageInfos:      file_hzw_hzw_proto_msgTypes,
	}.Build()
	File_hzw_hzw_proto = out.File
	file_hzw_hzw_proto_goTypes = nil
	file_hzw_hzw_proto_depIdxs = nil
}
