// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
//
// GenScope: package_group
// Versions:
//   - agserver: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressb/stressb.proto

package stressb

import (
	"context"
)

// BService defines the server interface for the BService service.
type BService interface {
	EchoB(context.Context, *EchoBRequest) (*EchoBResponse, error)
}
