// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: stressb/stressb.proto

package stressb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoBRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoBRequest) Reset() {
	*x = EchoBRequest{}
	mi := &file_stressb_stressb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoBRequest) ProtoMessage() {}

func (x *EchoBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stressb_stressb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoBRequest.ProtoReflect.Descriptor instead.
func (*EchoBRequest) Descriptor() ([]byte, []int) {
	return file_stressb_stressb_proto_rawDescGZIP(), []int{0}
}

func (x *EchoBRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EchoBResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoBResponse) Reset() {
	*x = EchoBResponse{}
	mi := &file_stressb_stressb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoBResponse) ProtoMessage() {}

func (x *EchoBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stressb_stressb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoBResponse.ProtoReflect.Descriptor instead.
func (*EchoBResponse) Descriptor() ([]byte, []int) {
	return file_stressb_stressb_proto_rawDescGZIP(), []int{1}
}

func (x *EchoBResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_stressb_stressb_proto protoreflect.FileDescriptor

const file_stressb_stressb_proto_rawDesc = "" +
	"\n" +
	"\x15stressb/stressb.proto\x12\astressb\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/descriptor.proto\"\"\n" +
	"\fEchoBRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"!\n" +
	"\rEchoBResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2X\n" +
	"\bbService\x12L\n" +
	"\x05echoB\x12\x15.stressb.EchoBRequest\x1a\x16.stressb.EchoBResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*b\x01*\"\x06echo/bB\x19Z\x17ag_stress_b/api/stressbb\x06proto3"

var (
	file_stressb_stressb_proto_rawDescOnce sync.Once
	file_stressb_stressb_proto_rawDescData []byte
)

func file_stressb_stressb_proto_rawDescGZIP() []byte {
	file_stressb_stressb_proto_rawDescOnce.Do(func() {
		file_stressb_stressb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stressb_stressb_proto_rawDesc), len(file_stressb_stressb_proto_rawDesc)))
	})
	return file_stressb_stressb_proto_rawDescData
}

var file_stressb_stressb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stressb_stressb_proto_goTypes = []any{
	(*EchoBRequest)(nil),  // 0: stressb.EchoBRequest
	(*EchoBResponse)(nil), // 1: stressb.EchoBResponse
}
var file_stressb_stressb_proto_depIdxs = []int32{
	0, // 0: stressb.bService.echoB:input_type -> stressb.EchoBRequest
	1, // 1: stressb.bService.echoB:output_type -> stressb.EchoBResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stressb_stressb_proto_init() }
func file_stressb_stressb_proto_init() {
	if File_stressb_stressb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stressb_stressb_proto_rawDesc), len(file_stressb_stressb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stressb_stressb_proto_goTypes,
		DependencyIndexes: file_stressb_stressb_proto_depIdxs,
		MessageInfos:      file_stressb_stressb_proto_msgTypes,
	}.Build()
	File_stressb_stressb_proto = out.File
	file_stressb_stressb_proto_goTypes = nil
	file_stressb_stressb_proto_depIdxs = nil
}
