// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressb/stressb.proto

package adpinit

import (
	bservice "ag_stress_b/internal/adpgen/hertz/bservice"
)

func init() {
	AddFxAdapterOpt(bservice.FxBServiceHertzModule)
}
