// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressb/stressb.proto

package adpinit

import (
	bservice "ag_stress_b/internal/adpgen/kitex/bservice"
)

func init() {
	AddFxAdapterOpt(bservice.FxBServiceKitexModule)
}
