// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressa/stressa.proto

package aservice

import (
	hserver "ag-core/contribute/aghertz/server"
	fx "go.uber.org/fx"
)

var FxAServiceHertzModule = fx.Module("fx_AService_hertz",
	FxAService_EchoA_hertz_RegProvider,
)
var FxAService_EchoA_hertz_RegProvider = fx.Provide(
	hserver.NewFxServerRouteProvider(
		Router_AService_EchoA_0_POST_Hertz,
	),
)
