// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressa/stressa.proto

package aservice

import (
	hserver "ag-core/contribute/aghertz/server"
	stressa "ag_stress_a/api/stressa"
	"context"
	app "github.com/cloudwego/hertz/pkg/app"
	consts "github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Router_AService_EchoA_0_POST_Hertz
// @Name: EchoA
// @Method: POST
// @Path: echo/a
func Router_AService_EchoA_0_POST_Hertz(s stressa.AService) *hserver.Route {
	return &hserver.Route{
		HttpMethod:   "POST",
		RelativePath: "echo/a",
		Handlers:     append(make([]app.HandlerFunc, 0), _AService_EchoA_0_HTTP_Handler(s)),
	}
}

func _AService_EchoA_0_HTTP_Handler(s stressa.AService) func(ctx context.Context, c *app.RequestContext) {
	return func(ctx context.Context, c *app.RequestContext) {
		//var in = new(stressa.EchoARequest)
		var in stressa.EchoARequest
		// BindByContentType 当Method为GET时，会自动调用BindQuery，其他方法会调用对应Bind
		if err := c.BindByContentType(&in); err != nil {
			c.String(consts.StatusBadRequest, err.Error())
			return
		}

		resp, err := s.EchoA(ctx, &in)
		if err != nil {
			// TODO 增强异常处理
			c.String(consts.StatusInternalServerError, err.Error())
			return
		}

		// c.JSON 会自动将 Content-Type 设置为 application/json,
		c.JSON(consts.StatusOK, resp)
	}
}
