// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressb/stressb.proto

package bservice

import (
	akserver "ag-core/contribute/agkitex/server"
	fx "go.uber.org/fx"
)

// FxBServiceKitexModule fx module
var FxBServiceKitexModule = fx.Module("fx_BService_kitex",
	FxBServiceKitexRegProvider,
)

// FxBServiceKitexRegProvider fx provide
var FxBServiceKitexRegProvider = fx.Provide(

	akserver.NewFxAgKitexServiceRegistry(
		Register_BService_KitexServer,
	),
)
