// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressb/stressb.proto

package bservice

import (
	stressb "ag_stress_b/api/stressb"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var bServiceServiceMethods = map[string]kitex.MethodInfo{
	"echoB": kitex.NewMethodInfo(
		echoBHandler,
		newEchoBArgs,
		newEchoBResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	bServiceServiceInfo                = NewServiceInfo()
	bServiceServiceInfoForClient       = NewServiceInfoForClient()
	bServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return bServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return bServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return bServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "bService"
	handlerType := (*stressb.BService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range bServiceServiceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "stressb",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.14.1_by_aggen", // FIXME 模板生成时应该获取kitex版本
		Extra:           extra,
	}
	return svcInfo
}

func echoBHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(stressb.EchoBRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(stressb.BService).EchoB(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *EchoBArgs:
		success, err := handler.(stressb.BService).EchoB(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*EchoBResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newEchoBArgs() interface{} {
	return &EchoBArgs{}
}

func newEchoBResult() interface{} {
	return &EchoBResult{}
}

type EchoBArgs struct {
	Req *stressb.EchoBRequest
}

func (p *EchoBArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *EchoBArgs) Unmarshal(in []byte) error {
	msg := new(stressb.EchoBRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var EchoBArgs_Req_DEFAULT *stressb.EchoBRequest

func (p *EchoBArgs) GetReq() *stressb.EchoBRequest {
	if !p.IsSetReq() {
		return EchoBArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *EchoBArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *EchoBArgs) GetFirstArgument() interface{} {
	return p.Req
}

type EchoBResult struct {
	Success *stressb.EchoBResponse
}

var EchoBResult_Success_DEFAULT *stressb.EchoBResponse

func (p *EchoBResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *EchoBResult) Unmarshal(in []byte) error {
	msg := new(stressb.EchoBResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *EchoBResult) GetSuccess() *stressb.EchoBResponse {
	if !p.IsSetSuccess() {
		return EchoBResult_Success_DEFAULT
	}
	return p.Success
}

func (p *EchoBResult) SetSuccess(x interface{}) {
	p.Success = x.(*stressb.EchoBResponse)
}

func (p *EchoBResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EchoBResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) EchoB(ctx context.Context, Req *stressb.EchoBRequest) (r *stressb.EchoBResponse, err error) {
	var _args EchoBArgs
	_args.Req = Req
	var _result EchoBResult
	if err = p.c.Call(ctx, "echoB", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
