// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agservice: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - hello/hello.proto

package svcgen

import (
	ag_service "ag-core/ag/ag_service"
	hello "agdemoC/api/hello"
	service "agdemoC/internal/service"
	"context"
	"fmt"
	slog "log/slog"
)

// ServiceInfo interface level

var HelloServiceInfo = ag_service.NewServiceInfo(
	"api.hello",
	"Hello",
	(*hello.Hello)(nil),
)

var HelloPinghelloCallInfo = ag_service.NewCallInfo(
	HelloServiceInfo,
	"Pinghello",
	false,
	false,
)

var HelloCallInfos = map[string]*ag_service.CallInfo{
	"Pinghello": HelloPinghelloCallInfo,
}

// HelloProxy 服务代理
type HelloProxy struct {
	ag_service.AgServiceProxyBase
	impl *service.HelloImpl
}

// NewHelloProxy 创建HelloProxy
func NewHelloProxy(
	impl *service.HelloImpl,
	agServiceBuilder ag_service.AgServiceBuilder,
	mws []ag_service.MiddlewareProvider,
) (hello.Hello, error) {

	p := &HelloProxy{
		impl: impl,
		AgServiceProxyBase: ag_service.NewAgServiceProxyBase(
			HelloServiceInfo,
			HelloCallInfos,
		),
	}

	for _, cif := range p.CallInfos {
		if cif.IsClientStreaming() || cif.IsServerStreaming() {
			slog.Warn("agServiceProxy buildskip streaming method", "call_name", cif.CallName)
			continue
		}

		// 根据方法信息构建Endpoints
		oriEndpoint, err := p.getOriginalHandler(cif)
		if err != nil {
			return nil, err
		}
		endpoint, err := agServiceBuilder.BuildEndpointChain(
			cif,
			mws,
			oriEndpoint,
		)
		if err != nil {
			return nil, err
		}
		// 注册endpoint
		p.RegisterEndpoint(cif.CallName(), endpoint)
	}

	return p, nil
}

// Pinghello HelloProxy proxy
func (p *HelloProxy) Pinghello(ctx context.Context, req *hello.HelloRequest) (*hello.HelloReply, error) {
	endpoint := p.GetEndpoint("Pinghello")

	resp, err := endpoint(ctx, req)
	if err != nil {
		slog.Error("failed to handle request!", "method", "Pinghello", "error", err)
		return nil, err
	}

	return resp.(*hello.HelloReply), nil
}

// getOriginalHandler
func (p *HelloProxy) getOriginalHandler(cif *ag_service.CallInfo) (ag_service.Endpoint, error) {
	switch cif.CallName() {
	case "Pinghello":
		return func(ctx context.Context, req interface{}) (interface{}, error) {
			return p.impl.Pinghello(ctx, req.(*hello.HelloRequest))
		}, nil
	default:
		return nil, fmt.Errorf("handler for method %s not implemented", cif.CallName)
	}
}
