// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
//
// GenScope: package_group
// Versions:
//   - agservice: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - hello/hello.proto

package svcgen

import (
	ag_service "ag-core/ag/ag_service"
	hello "agdemoC/api/hello"
	service "agdemoC/internal/service"
	fx "go.uber.org/fx"
)

// FxInHelloMiddleware servcie middleware inject params
type FxInHelloMiddleware struct {
	fx.In

	AgServiceBuilder ag_service.AgServiceBuilder

	CustomMws []ag_service.MiddlewareProvider `group:"fx_hello_service_middleware" ,optional:"true"`
}

// NewHelloProxyWithFxIn create Hello proxy with fx inject
func NewHelloProxyWithFxIn(in FxInHelloMiddleware, svc *service.HelloImpl) (hello.Hello, error) {
	return NewHelloProxy(svc, in.AgServiceBuilder, in.CustomMws)
}

func init() {
	AddFxServiceWithProxyOpt(
		fx.Provide(
			service.NewHelloImpl, // constructor return impl
			NewHelloProxyWithFxIn,
		),
	)
}
