// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demob/demoB.proto

package adpinit

import (
	demob "agdemoB/internal/adpgen/kitex/demob"
)

func init() {
	AddFxAdapterOpt(demob.FxDemobKitexModule)
}
