// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demob/demoB2.proto

package adpinit

import (
	demobsvc2 "agdemoB/internal/adpgen/kitex/demobsvc2"
)

func init() {
	AddFxAdapterOpt(demobsvc2.FxDemobsvc2KitexModule)
}
