// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demob/demoB2.proto

package adpinit

import (
	demobsvc2 "agdemoB/internal/adpgen/hertz/demobsvc2"
)

func init() {
	AddFxAdapterOpt(demobsvc2.FxDemobsvc2HertzModule)
}
