// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demob/demoB.proto

package adpinit

import (
	demob "agdemoB/internal/adpgen/hertz/demob"
)

func init() {
	AddFxAdapterOpt(demob.FxDemobHertzModule)
}
