// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - hello/hello.proto

package hello

import (
	agclient "ag-core/contribute/aghertz/aghertzclient"
	hello "agdemoA/api/hello"
	"context"

	"github.com/cloudwego/hertz/pkg/app/client"
	config "github.com/cloudwego/hertz/pkg/common/config"
)

// HelloHertzClient is the hertz client for Hello.
type HelloHertzClient interface {
	// Pinghello
	Pinghello(ctx context.Context, req *hello.HelloRequest, opts ...config.RequestOption) (resp *hello.HelloReply, err error)
}

// NewHelloHertzClient is the constructor for HelloHertzClient.
func NewHelloHertzClient(hc *client.Client, opts ...agclient.AgHertzClientOption) HelloHertzClient {
	client := &HelloHertzClientImpl{
		HertzBaseClient: agclient.NewHertzBaseClient(hc, opts...),
	}
	return client
}

// HelloHertzClientImpl is the hertz client impl for Hello.
type HelloHertzClientImpl struct {
	*agclient.HertzBaseClient
}

// Pinghello client impl Pinghello
func (c *HelloHertzClientImpl) Pinghello(ctx context.Context, req *hello.HelloRequest, opts ...config.RequestOption) (*hello.HelloReply, error) {
	var resp hello.HelloReply

	// 构建请求配置
	reqParam := &agclient.RequestParam{
		Method: "POST",
		Path:   "pinghello",
	}
	rerr := c.DoRequest(ctx, reqParam, req, &resp, opts...)
	if rerr != nil {
		return nil, rerr
	}

	return &resp, nil
}
