// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agservice: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demoa/demoA.proto

package svcgen

import (
	ag_service "ag-core/ag/ag_service"
	demoa "agdemoA/api/demoa"
	service "agdemoA/internal/service"
	"context"
	"fmt"
	slog "log/slog"
)

// ServiceInfo interface level

var DemoAServiceInfo = ag_service.NewServiceInfo(
	"demoa",
	"DemoA",
	(*demoa.DemoA)(nil),
)

var DemoACalldemoaCallInfo = ag_service.NewCallInfo(
	DemoAServiceInfo,
	"Calldemoa",
	false,
	false,
)

var DemoACallInfos = map[string]*ag_service.CallInfo{
	"Calldemoa": DemoACalldemoaCallInfo,
}

// DemoAProxy 服务代理
type DemoAProxy struct {
	ag_service.AgServiceProxyBase
	impl *service.DemoAImpl
}

// NewDemoAProxy 创建DemoAProxy
func NewDemoAProxy(
	impl *service.DemoAImpl,
	agServiceBuilder ag_service.AgServiceBuilder,
	mws []ag_service.MiddlewareProvider,
) (demoa.DemoA, error) {

	p := &DemoAProxy{
		impl: impl,
		AgServiceProxyBase: ag_service.NewAgServiceProxyBase(
			DemoAServiceInfo,
			DemoACallInfos,
		),
	}

	for _, cif := range p.CallInfos {
		if cif.IsClientStreaming() || cif.IsServerStreaming() {
			slog.Warn("agServiceProxy buildskip streaming method", "call_name", cif.CallName)
			continue
		}

		// 根据方法信息构建Endpoints
		oriEndpoint, err := p.getOriginalHandler(cif)
		if err != nil {
			return nil, err
		}
		endpoint, err := agServiceBuilder.BuildEndpointChain(
			cif,
			mws,
			oriEndpoint,
		)
		if err != nil {
			return nil, err
		}
		// 注册endpoint
		p.RegisterEndpoint(cif.CallName(), endpoint)
	}

	return p, nil
}

// Calldemoa DemoAProxy proxy
func (p *DemoAProxy) Calldemoa(ctx context.Context, req *demoa.ARequest) (*demoa.AReply, error) {
	endpoint := p.GetEndpoint("Calldemoa")

	resp, err := endpoint(ctx, req)
	if err != nil {
		slog.Error("failed to handle request!", "method", "Calldemoa", "error", err)
		return nil, err
	}

	return resp.(*demoa.AReply), nil
}

// getOriginalHandler
func (p *DemoAProxy) getOriginalHandler(cif *ag_service.CallInfo) (ag_service.Endpoint, error) {
	switch cif.CallName() {
	case "Calldemoa":
		return func(ctx context.Context, req interface{}) (interface{}, error) {
			return p.impl.Calldemoa(ctx, req.(*demoa.ARequest))
		}, nil
	default:
		return nil, fmt.Errorf("handler for method %s not implemented", cif.CallName)
	}
}
