// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
//
// GenScope: package_group
// Versions:
//   - agservice: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demoa/demoA.proto

package svcgen

import (
	ag_service "ag-core/ag/ag_service"
	demoa "agdemoA/api/demoa"
	service "agdemoA/internal/service"
	fx "go.uber.org/fx"
)

// FxInDemoAMiddleware servcie middleware inject params
type FxInDemoAMiddleware struct {
	fx.In

	AgServiceBuilder ag_service.AgServiceBuilder

	CustomMws []ag_service.MiddlewareProvider `group:"fx_demoa_service_middleware" ,optional:"true"`
}

// NewDemoAProxyWithFxIn create DemoA proxy with fx inject
func NewDemoAProxyWithFxIn(in FxInDemoAMiddleware, svc *service.DemoAImpl) (demoa.DemoA, error) {
	return NewDemoAProxy(svc, in.AgServiceBuilder, in.CustomMws)
}

func init() {
	AddFxServiceWithProxyOpt(
		fx.Provide(
			service.NewDemoAImpl, // constructor return impl
			NewDemoAProxyWithFxIn,
		),
	)
}
