// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
//
// GenScope: package_group
// Versions:
//   - agserver: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressc/stressc.proto

package stressc

import (
	"context"
)

// CService defines the server interface for the CService service.
type CService interface {
	EchoC(context.Context, *EchoCRequest) (*EchoCResponse, error)
}
