// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agservice: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demob/demoB.proto

package svcgen

import (
	ag_service "ag-core/ag/ag_service"
	demob "agdemoB/api/demob"
	service "agdemoB/internal/service"
	"context"
	"fmt"
	slog "log/slog"
)

// ServiceInfo interface level

var DemobServiceInfo = ag_service.NewServiceInfo(
	"api.demob",
	"Demob",
	(*demob.Demob)(nil),
)

var DemobCalldemobCallInfo = ag_service.NewCallInfo(
	DemobServiceInfo,
	"Calldemob",
	false,
	false,
)

var DemobCallInfos = map[string]*ag_service.CallInfo{
	"Calldemob": DemobCalldemobCallInfo,
}

// DemobProxy 服务代理
type DemobProxy struct {
	ag_service.AgServiceProxyBase
	impl *service.DemobImpl
}

// NewDemobProxy 创建DemobProxy
func NewDemobProxy(
	impl *service.DemobImpl,
	agServiceBuilder ag_service.AgServiceBuilder,
	mws []ag_service.MiddlewareProvider,
) (demob.Demob, error) {

	p := &DemobProxy{
		impl: impl,
		AgServiceProxyBase: ag_service.NewAgServiceProxyBase(
			DemobServiceInfo,
			DemobCallInfos,
		),
	}

	for _, cif := range p.CallInfos {
		if cif.IsClientStreaming() || cif.IsServerStreaming() {
			slog.Warn("agServiceProxy buildskip streaming method", "call_name", cif.CallName)
			continue
		}

		// 根据方法信息构建Endpoints
		oriEndpoint, err := p.getOriginalHandler(cif)
		if err != nil {
			return nil, err
		}
		endpoint, err := agServiceBuilder.BuildEndpointChain(
			cif,
			mws,
			oriEndpoint,
		)
		if err != nil {
			return nil, err
		}
		// 注册endpoint
		p.RegisterEndpoint(cif.CallName(), endpoint)
	}

	return p, nil
}

// Calldemob DemobProxy proxy
func (p *DemobProxy) Calldemob(ctx context.Context, req *demob.BRequest) (*demob.BReply, error) {
	endpoint := p.GetEndpoint("Calldemob")

	resp, err := endpoint(ctx, req)
	if err != nil {
		slog.Error("failed to handle request!", "method", "Calldemob", "error", err)
		return nil, err
	}

	return resp.(*demob.BReply), nil
}

// getOriginalHandler
func (p *DemobProxy) getOriginalHandler(cif *ag_service.CallInfo) (ag_service.Endpoint, error) {
	switch cif.CallName() {
	case "Calldemob":
		return func(ctx context.Context, req interface{}) (interface{}, error) {
			return p.impl.Calldemob(ctx, req.(*demob.BRequest))
		}, nil
	default:
		return nil, fmt.Errorf("handler for method %s not implemented", cif.CallName)
	}
}
