// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agservice: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demob/demoB2.proto

package svcgen

import (
	ag_service "ag-core/ag/ag_service"
	demob "agdemoB/api/demob"
	service "agdemoB/internal/service"
	"context"
	"fmt"
	slog "log/slog"
)

// ServiceInfo interface level

var Demobsvc2ServiceInfo = ag_service.NewServiceInfo(
	"api.demob",
	"Demobsvc2",
	(*demob.Demobsvc2)(nil),
)

var Demobsvc2HelloCallInfo = ag_service.NewCallInfo(
	Demobsvc2ServiceInfo,
	"Hello",
	false,
	false,
)

var Demobsvc2CallInfos = map[string]*ag_service.CallInfo{
	"Hello": Demobsvc2HelloCallInfo,
}

// Demobsvc2Proxy 服务代理
type Demobsvc2Proxy struct {
	ag_service.AgServiceProxyBase
	impl *service.Demobsvc2Impl
}

// NewDemobsvc2Proxy 创建Demobsvc2Proxy
func NewDemobsvc2Proxy(
	impl *service.Demobsvc2Impl,
	agServiceBuilder ag_service.AgServiceBuilder,
	mws []ag_service.MiddlewareProvider,
) (demob.Demobsvc2, error) {

	p := &Demobsvc2Proxy{
		impl: impl,
		AgServiceProxyBase: ag_service.NewAgServiceProxyBase(
			Demobsvc2ServiceInfo,
			Demobsvc2CallInfos,
		),
	}

	for _, cif := range p.CallInfos {
		if cif.IsClientStreaming() || cif.IsServerStreaming() {
			slog.Warn("agServiceProxy buildskip streaming method", "call_name", cif.CallName)
			continue
		}

		// 根据方法信息构建Endpoints
		oriEndpoint, err := p.getOriginalHandler(cif)
		if err != nil {
			return nil, err
		}
		endpoint, err := agServiceBuilder.BuildEndpointChain(
			cif,
			mws,
			oriEndpoint,
		)
		if err != nil {
			return nil, err
		}
		// 注册endpoint
		p.RegisterEndpoint(cif.CallName(), endpoint)
	}

	return p, nil
}

// Hello Demobsvc2Proxy proxy
func (p *Demobsvc2Proxy) Hello(ctx context.Context, req *demob.BReq2) (*demob.BRep2, error) {
	endpoint := p.GetEndpoint("Hello")

	resp, err := endpoint(ctx, req)
	if err != nil {
		slog.Error("failed to handle request!", "method", "Hello", "error", err)
		return nil, err
	}

	return resp.(*demob.BRep2), nil
}

// getOriginalHandler
func (p *Demobsvc2Proxy) getOriginalHandler(cif *ag_service.CallInfo) (ag_service.Endpoint, error) {
	switch cif.CallName() {
	case "Hello":
		return func(ctx context.Context, req interface{}) (interface{}, error) {
			return p.impl.Hello(ctx, req.(*demob.BReq2))
		}, nil
	default:
		return nil, fmt.Errorf("handler for method %s not implemented", cif.CallName)
	}
}
