// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
//
// GenScope: package_group
// Versions:
//   - agservice: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - demob/demoB.proto
//   - demob/demoB2.proto

package svcgen

import (
	ag_service "ag-core/ag/ag_service"
	demob "agdemoB/api/demob"
	service "agdemoB/internal/service"
	fx "go.uber.org/fx"
)

// FxInDemobMiddleware servcie middleware inject params
type FxInDemobMiddleware struct {
	fx.In

	AgServiceBuilder ag_service.AgServiceBuilder

	CustomMws []ag_service.MiddlewareProvider `group:"fx_demob_service_middleware" ,optional:"true"`
}

// NewDemobProxyWithFxIn create Demob proxy with fx inject
func NewDemobProxyWithFxIn(in FxInDemobMiddleware, svc *service.DemobImpl) (demob.Demob, error) {
	return NewDemobProxy(svc, in.AgServiceBuilder, in.CustomMws)
}

// FxInDemobsvc2Middleware servcie middleware inject params
type FxInDemobsvc2Middleware struct {
	fx.In

	AgServiceBuilder ag_service.AgServiceBuilder

	CustomMws []ag_service.MiddlewareProvider `group:"fx_demobsvc2_service_middleware" ,optional:"true"`
}

// NewDemobsvc2ProxyWithFxIn create Demobsvc2 proxy with fx inject
func NewDemobsvc2ProxyWithFxIn(in FxInDemobsvc2Middleware, svc *service.Demobsvc2Impl) (demob.Demobsvc2, error) {
	return NewDemobsvc2Proxy(svc, in.AgServiceBuilder, in.CustomMws)
}

func init() {
	AddFxServiceWithProxyOpt(
		fx.Provide(
			service.NewDemobImpl, // constructor return impl
			NewDemobProxyWithFxIn,
			service.NewDemobsvc2Impl, // constructor return impl
			NewDemobsvc2ProxyWithFxIn,
		),
	)
}
