// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agservice: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressb/stressb.proto

package svcgen

import (
	ag_service "ag-core/ag/ag_service"
	stressb "ag_stress_b/api/stressb"
	service "ag_stress_b/internal/service"
	"context"
	"fmt"
	slog "log/slog"
)

// ServiceInfo interface level

var BServiceServiceInfo = ag_service.NewServiceInfo(
	"stressb",
	"BService",
	(*stressb.BService)(nil),
)

var BServiceEchoBCallInfo = ag_service.NewCallInfo(
	BServiceServiceInfo,
	"EchoB",
	false,
	false,
)

var BServiceCallInfos = map[string]*ag_service.CallInfo{
	"EchoB": BServiceEchoBCallInfo,
}

// BServiceProxy 服务代理
type BServiceProxy struct {
	ag_service.AgServiceProxyBase
	impl *service.BServiceImpl
}

// NewBServiceProxy 创建BServiceProxy
func NewBServiceProxy(
	impl *service.BServiceImpl,
	agServiceBuilder ag_service.AgServiceBuilder,
	mws []ag_service.MiddlewareProvider,
) (stressb.BService, error) {

	p := &BServiceProxy{
		impl: impl,
		AgServiceProxyBase: ag_service.NewAgServiceProxyBase(
			BServiceServiceInfo,
			BServiceCallInfos,
		),
	}

	for _, cif := range p.CallInfos {
		if cif.IsClientStreaming() || cif.IsServerStreaming() {
			slog.Warn("agServiceProxy buildskip streaming method", "call_name", cif.CallName)
			continue
		}

		// 根据方法信息构建Endpoints
		oriEndpoint, err := p.getOriginalHandler(cif)
		if err != nil {
			return nil, err
		}
		endpoint, err := agServiceBuilder.BuildEndpointChain(
			cif,
			mws,
			oriEndpoint,
		)
		if err != nil {
			return nil, err
		}
		// 注册endpoint
		p.RegisterEndpoint(cif.CallName(), endpoint)
	}

	return p, nil
}

// EchoB BServiceProxy proxy
func (p *BServiceProxy) EchoB(ctx context.Context, req *stressb.EchoBRequest) (*stressb.EchoBResponse, error) {
	endpoint := p.GetEndpoint("EchoB")

	resp, err := endpoint(ctx, req)
	if err != nil {
		slog.Error("failed to handle request!", "method", "EchoB", "error", err)
		return nil, err
	}

	return resp.(*stressb.EchoBResponse), nil
}

// getOriginalHandler
func (p *BServiceProxy) getOriginalHandler(cif *ag_service.CallInfo) (ag_service.Endpoint, error) {
	switch cif.CallName() {
	case "EchoB":
		return func(ctx context.Context, req interface{}) (interface{}, error) {
			return p.impl.EchoB(ctx, req.(*stressb.EchoBRequest))
		}, nil
	default:
		return nil, fmt.Errorf("handler for method %s not implemented", cif.CallName)
	}
}
