// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
//
// GenScope: package_group
// Versions:
//   - agservice: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - stressb/stressb.proto

package svcgen

import (
	ag_service "ag-core/ag/ag_service"
	stressb "ag_stress_b/api/stressb"
	service "ag_stress_b/internal/service"
	fx "go.uber.org/fx"
)

// FxInBServiceMiddleware servcie middleware inject params
type FxInBServiceMiddleware struct {
	fx.In

	AgServiceBuilder ag_service.AgServiceBuilder

	CustomMws []ag_service.MiddlewareProvider `group:"fx_bservice_service_middleware" ,optional:"true"`
}

// NewBServiceProxyWithFxIn create BService proxy with fx inject
func NewBServiceProxyWithFxIn(in FxInBServiceMiddleware, svc *service.BServiceImpl) (stressb.BService, error) {
	return NewBServiceProxy(svc, in.AgServiceBuilder, in.CustomMws)
}

func init() {
	AddFxServiceWithProxyOpt(
		fx.Provide(
			service.NewBServiceImpl, // constructor return impl
			NewBServiceProxyWithFxIn,
		),
	)
}
